### ISSUE TITLE
请问能自己设置H@H代理来下载图片吗？

### ISSUE THREAD

**Issue by CheapLolicon** [fffonion/xeHentai#11]
因为自己设置H@H代理后浏览图片也快些了，浏览图片和该下载器是一样原理的吧？
所以我在想，能否设置H@H代理来提高自己下载速度和下载图片的成功率……

**Comment by fffonion** [comment]
不行，但是可以考虑加入换源的功能（网页上有click here if image fails loading)

**Comment by CheapLolicon** [comment]
噢……多谢作者大大的回复，我先去看看

**Comment by fffonion** [comment]
嗯…其实可以参考这个项目重新写一个，这个写得太恶心了，我自己都不会改了

**Comment by fffonion** [comment]
2.0版本可以在网页端设置后通过RPC发送到xeHentai，这样xeHentai就会解析到通过h@h下载

**Comment by dennySORA** [comment]
@fffonion 請問一下，該如何設置才能轉到H＠H來下載。
謝謝～

**Comment by fffonion** [comment]
@dennySORA 在e站上配置使用h@h加载，用同一个账号登录xehentai，使用RPC添加任务到xehentai就可以了
