### ISSUE TITLE
windows 7 下 出现 Traceback (most recent call last) 错误

### ISSUE THREAD

**Issue by freeocha** [fffonion/xeHentai#13]
系统环境： windows 7 (64bit)
软件版本：xeHentai-1.5.4.999.exe

之前在ex站 想收一个 600多页的CG， 发现每下载十几页 收割机 就会 重试
于是把系统的temp文件夹清空了（近25G)，eh.log也删掉

结果再次使用的时候 发生错误：
Traceback (most recent call last):
  File "< string>", line 494, in < module>
  File "< string>", line 206, in query_info
IndexError: list index out of range

求大大帮忙

**Comment by fffonion** [comment]
查询ip的那个网站域名过期了……
![qq 20160331195324](https://cloud.githubusercontent.com/assets/2135445/14187297/56daf00e-f750-11e5-8b83-3d1a5be45a3d.png)
