### ISSUE TITLE
一直沒辦法載完全圖片...只能載個幾張..版本1.5.4.9992

### ISSUE THREAD

**Issue by ciciwon4** [fffonion/xeHentai#14]
----------------------查詢配額及IP信息--------------------
當前IP 36.239.60.195
Sibylla system: 下載H@H索引……
Sibylla system: 目標已鎖定 [tosh] ！ [春蛋漢化][無修正by zoi
Sibylla system: 圖片被縮放，進行完整掃描
19:13:28 - 執行官: 已啟動.
19:13:29 - 執行官: http://exhentai.org/g/424844/14650fa68d/?p=0
19:13:29 - 執行官: http://exhentai.org/g/424844/14650fa68d/?p=1
19:13:30 - 執行官: http://exhentai.org/g/424844/14650fa68d/?p=2
19:13:30 - 執行官: http://exhentai.org/g/424844/14650fa68d/?p=3
19:13:30 - 執行官: http://exhentai.org/g/424844/14650fa68d/?p=4
19:13:31 - 執行官: http://exhentai.org/g/424844/14650fa68d/?p=5
19:13:31 - 執行官: 已退出.
          -------------------下載開始. 下載 213 張圖片 -------------
19:13:32 - 執行官+: 已啟動.
19:13:32 - 收割機1: 已啟動.
19:13:32 - 收割機2: 已啟動.
19:13:33 - 收割機3: 已啟動.
19:13:33 - 收割機4: 已啟動.
19:13:33 - 收割機5: 已啟動.
19:13:33 - 執行官+: http://exhentai.org/s/b740c9c499/424844-1
19:13:33 - 執行官+: http://exhentai.org/s/fcc447cd45/424844-2
19:13:34 - 執行官+: http://exhentai.org/s/30783ff6b6/424844-3
19:13:34 - 收割機2: #001 000a.jpg (781833) 下載完成.
19:13:34 - 執行官+: http://exhentai.org/s/d5beef4b4a/424844-4
19:13:34 - 執行官+: http://exhentai.org/s/a41bfb6cb4/424844-5
19:13:34 - 執行官+: http://exhentai.org/s/c44de8d5b8/424844-6
19:13:35 - 收割機5: #005 000e.jpg (246201) 下載完成.
19:13:35 - 執行官+: http://exhentai.org/s/af982ba8b4/424844-7
19:13:35 - 收割機3: #004 000d.jpg (681545) 下載完成.
19:13:35 - 執行官+: http://exhentai.org/s/572fb11367/424844-8
19:13:35 - 收割機4: #006 000f.jpg (215261) 下載完成.
19:13:36 - 執行官+: http://exhentai.org/s/c01ea796d3/424844-9
19:13:36 - 執行官+: http://exhentai.org/s/c01ea796d3/424844-10
19:13:36 - 收割機3: #009 001c.jpg (10936) 下載完成.
19:13:36 - 收割機3: #010 001d.jpg (10936) 下載完成.
19:13:36 - 執行官+: http://exhentai.org/s/afa5041403/424844-11
19:13:37 - 收割機1: #002 000b.jpg (781932) 下載完成.
19:13:37 - 執行官+: http://exhentai.org/s/973b62502a/424844-12
19:13:37 - 收割機4: #008 001bd.jpg (647556) 下載完成.
19:13:37 - 執行官+: http://exhentai.org/s/583689902b/424844-13
19:13:38 - 收割機1: #011 002a.jpg (534867) 下載完成.
19:13:38 - 執行官+: http://exhentai.org/s/d88311f4c5/424844-14
19:13:38 - 執行官+: http://exhentai.org/s/ddced8957e/424844-15
19:13:38 - 執行官+: http://exhentai.org/s/02f2befd54/424844-16
19:13:38 - 執行官+: http://exhentai.org/s/685ad72e40/424844-17
19:13:39 - 執行官+: http://exhentai.org/s/54087ab813/424844-18
19:13:39 - 執行官+: http://exhentai.org/s/8a566aad9a/424844-19
19:13:39 - 收割機1: #013 003d.jpg (657030) 下載完成.
19:13:39 - 收割機4: #014 004d.jpg (606309) 下載完成.
19:13:39 - 執行官+: http://exhentai.org/s/68c322789c/424844-20
Exception in thread ?嗅??:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "<string>", line 410, in run
Exception: Server Error

19:13:40 - 收割機2: #003 000c.jpg (470236) 下載完成.
19:13:40 - 收割機3: #012 002bd.jpg (636098) 下載完成.
19:13:40 - 執行官+: http://exhentai.org/s/09f1e0a087/424844-21
19:13:40 - 收割機4: #016 006d.jpg (788180) 下載完成.
19:13:40 - 收割機3: #018 008d.jpg (675839) 下載完成.
19:13:41 - 執行官+: http://exhentai.org/s/902bef3e48/424844-22
19:13:41 - 收割機1: #015 005d.jpg (675131) 下載完成.
19:13:41 - 執行官+: http://exhentai.org/s/13a75741bc/424844-23
19:13:41 - 執行官+: http://exhentai.org/s/1de32ec063/424844-24
19:13:41 - 收割機1: #021 011.jpg (387055) 下載完成.
19:13:42 - 收割機3: #020 010d.jpg (631628) 下載完成.
19:13:42 - 執行官+: http://exhentai.org/s/1649faba47/424844-25
19:13:42 - 執行官+: http://exhentai.org/s/9aa0c8cf8e/424844-26
19:13:42 - 執行官+: http://exhentai.org/s/fb1b1e8dc8/424844-27
19:13:42 - 監視官 : 4個收割機存活, 共 5個.
19:13:42 - 執行官+: http://exhentai.org/s/a2fb9c24f1/424844-28
19:13:43 - 執行官+: http://exhentai.org/s/7a431ce847/424844-29
19:13:43 - 執行官+: http://exhentai.org/s/f2875bd568/424844-30
19:13:43 - 收割機1: #022 012d.jpg (781303) 下載完成.
19:13:43 - 執行官+: http://exhentai.org/s/6b1aa3947f/424844-31
19:13:44 - 執行官+: http://exhentai.org/s/e05f7c6199/424844-32
19:13:44 - 收割機1: #024 014d.jpg (636770) 下載完成.
Exception in thread ?扯?摰?:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "<string>", line 405, in run
  File "<string>", line 154, in getpicurl
IndexError: list index out of range

19:13:44 - 執行官+: http://exhentai.org/s/14c851c208/424844-33
19:13:44 - 收割機1: #025 015d.jpg (755766) 下載完成.
Exception in thread ?嗅??:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "<string>", line 383, in run
KeyError: 'content-length'

19:13:44 - 執行官+: http://exhentai.org/s/cf9997cb9e/424844-34
19:13:45 - 執行官+: http://exhentai.org/s/0ac40dc803/424844-35
19:13:45 - 收割機5: #007 001ad.jpg (834783) 下載完成.
19:13:45 - 收割機5: #027 017d.jpg (527241) 下載完成.
19:13:47 - 收割機3: #023 013d.jpg (728301) 下載完成.
19:13:47 - 收割機5: #028 018d.jpg (674432) 下載完成.
19:13:49 - 收割機5: #030 020d.jpg (754789) 下載完成.
19:13:50 - 收割機5: #031 021.jpg (478093) 下載完成.
19:13:50 - 收割機3: #029 019d.jpg (688719) 下載完成.
19:13:50 - 收割機5: #032 022.jpg (430425) 下載完成.
19:13:50 - 收割機5: #034 024.jpg (480452) 下載完成.
19:13:50 - 收割機3: #033 023.jpg (416190) 下載完成.
19:13:51 - 收割機3: 已退出.
19:13:52 - 收割機1: #026 016d.jpg (724488) 下載完成.
19:13:52 - 監視官 : 1個收割機存活, 共 5個.
19:13:53 - 收割機1: 已退出.
19:13:59 - 收割機5: #035 025.jpg (427808) 下載完成.
19:13:59 - 收割機5: 已退出.
          ------------------------下載結束.------------------------
[tosh] ！ [春蛋漢化][無修正by zoidsking] 下載完成！
是否重命名回原始名稱? y/n(默認):

**Comment by fffonion** [comment]
试一下9993？

**Comment by ciciwon4** [comment]
-------------------下載開始. 下載 35 張圖片 -------------------
19:58:56 - 執行官+: 已啟動.
19:58:56 - 執行官+: 已退出.
Exception in thread ?嗅??:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "<string>", line 413, in run
Exception: Server Error

19:58:56 - 收割機1: 已啟動.
19:58:56 - 收割機2: 已啟動.
Exception in thread ?嗅??:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "<string>", line 413, in run
Exception: Server Error

19:58:57 - 收割機3: 已啟動.
19:58:57 - 收割機4: 已啟動.
19:58:57 - 收割機5: 已啟動.
19:58:57 - 收割機1: #001 000a.jpg (781833) 下載完成.
19:58:57 - 收割機2: #002 000b.jpg (781932) 下載完成.
19:58:58 - 收割機3: #003 000c.jpg (470236) 下載完成.
19:58:58 - 收割機4: #004 000d.jpg (681545) 下載完成.
19:58:58 - 收割機5: #005 000e.jpg (246201) 下載完成.
19:58:58 - 收割機1: #006 000f.jpg (215261) 下載完成.
19:58:58 - 收割機4: #009 001c.jpg (10936) 下載完成.
19:58:59 - 收割機2: #007 001ad.jpg (834783) 下載完成.
19:58:59 - 收割機3: #008 001bd.jpg (647556) 下載完成.
19:58:59 - 收割機5: #010 001d.jpg (10936) 下載完成.
19:58:59 - 收割機1: #011 002a.jpg (534867) 下載完成.
19:58:59 - 收割機4: #012 002bd.jpg (636098) 下載完成.
19:59:00 - 收割機2: #013 003d.jpg (657030) 下載完成.
19:59:00 - 收割機3: #014 004d.jpg (606309) 下載完成.
19:59:00 - 收割機5: #015 005d.jpg (675131) 下載完成.
19:59:00 - 收割機1: #016 006d.jpg (788180) 下載完成.
19:59:00 - 收割機2: #018 008d.jpg (675839) 下載完成.
19:59:01 - 收割機1: #021 011.jpg (387055) 下載完成.
19:59:01 - 收割機5: #020 010d.jpg (631628) 下載完成.
19:59:01 - 收割機2: #022 012d.jpg (781303) 下載完成.
19:59:01 - 收割機1: #023 013d.jpg (728301) 下載完成.
19:59:01 - 收割機5: #024 014d.jpg (636770) 下載完成.
19:59:02 - 收割機5: #027 017d.jpg (527241) 下載完成.
19:59:02 - 收割機2: #025 015d.jpg (755766) 下載完成.
19:59:02 - 收割機1: #026 016d.jpg (724488) 下載完成.
19:59:02 - 收割機2: #029 019d.jpg (688719) 下載完成.
19:59:03 - 收割機1: #030 020d.jpg (754789) 下載完成.
19:59:03 - 收割機5: #028 018d.jpg (674432) 下載完成.
19:59:03 - 收割機2: #031 021.jpg (478093) 下載完成.
19:59:03 - 收割機1: #032 022.jpg (430425) 下載完成.
19:59:03 - 收割機5: #033 023.jpg (416190) 下載完成.
19:59:04 - 收割機5: 已退出.
19:59:04 - 收割機1: #035 025.jpg (427808) 下載完成.
19:59:04 - 收割機1: 已退出.
19:59:04 - 收割機2: #034 024.jpg (480452) 下載完成.
19:59:04 - 收割機2: 已退出.
          ------------------------下載結束.------------------------
[tosh] ！ [春蛋漢化][無修正by zoidsking] 下載完成！
是否重命名回原始名稱? y/n(默認):

 變這樣...

**Comment by fffonion** [comment]
这个server error你只能多开几次重新下了

**Comment by ciciwon4** [comment]
非常感謝您的更新!!
