### ISSUE TITLE
輸入地址無法運作

### ISSUE THREAD

**Issue by ciciwon4** [fffonion/xeHentai#16]
紳♂士下載器 v1.549994
          --------------------從文件加載了Cookies--------------------
輸入地址(使用,分割下載多個)： https://exhentai.org/g/909216/de98b6115b/
          ------------------------咦?這是啥------------------------
輸入地址(使用,分割下載多個)： https://exhentai.org/g/909216/de98b6115b/
          ------------------------咦?這是啥------------------------
輸入地址(使用,分割下載多個)：

**Comment by fffonion** [comment]
请尝试使用1.5.4.9995
