### ISSUE TITLE
2.0.0.9版会下载无效的图片

### ISSUE THREAD

**Issue by freeocha** [fffonion/xeHentai#20]
版本：xeHentai-2.0.0.9
系统：windows 10 64bit

以往使用1.5.4版时，遇到加载失败的图片会有重试5次失败的显示。

而2.0.0.9版会下载一个20多byte的无效文件然后继续下载后面的图片。这样虽然方便，但是没有加载失败的提示，很容易被忽略。能否在最后加入哪些图片加载失败的提示？

**Comment by fffonion** [comment]
嗯，这样不对。下载20byte内容是什么？

**Comment by freeocha** [comment]
用记事本打开后， 写着 “An error has occurred. (404)”
如果需要，我可以上传文件

**Comment by fffonion** [comment]
哦这个是h@h的错误，但是按道理应该不会出现404。能否将log_verbose设置为3然后下载完成后附一下eh.log？

**Comment by freeocha** [comment]
抱歉，不懂编程，log_verbose这个文件在哪里？

**Comment by fffonion** [comment]
记事本打开config.py找到log_verbose=2修改为3

**Comment by freeocha** [comment]
p28 就是20多byte的文件


[Aug 18 22:40:03] 任务 #a84c6366 标题 [柚木N’] ずっと好きだった 第4話 (COMIC 夢幻転生 2014年12月号) [中国翻訳]
[Aug 18 22:40:03] 任务 #a84c6366 将下载29个文件，共29个 
[Aug 18 22:40:03] t-scan-1 start
[Aug 18 22:40:03] t-down-1 start
[Aug 18 22:40:03] t-down-2 start
[Aug 18 22:40:03] t-down-3 start
[Aug 18 22:40:03] 程序循环已完成
[Aug 18 22:40:03] t-down-4 start
[Aug 18 22:40:05] 绅士-scan-1 GET https://exhentai.org/s/5795c593f6/792572-1 200 3892
[Aug 18 22:40:05] 绅士-scan-1 GET https://exhentai.org/s/c51b5f41fa/792572-2 200 3885
[Aug 18 22:40:05] 绅士-scan-1 GET https://exhentai.org/s/a32938cf99/792572-3 200 3884
[Aug 18 22:40:06] 绅士-scan-1 GET https://exhentai.org/s/5ecdfd0d80/792572-4 200 3883
[Aug 18 22:40:06] 绅士-scan-1 GET https://exhentai.org/s/72f09bf547/792572-5 200 3885
[Aug 18 22:40:06] 绅士-scan-1 GET https://exhentai.org/s/6817c2b33a/792572-6 200 3883
[Aug 18 22:40:07] 绅士-scan-1 GET https://exhentai.org/s/a1fd99424b/792572-7 200 3882
[Aug 18 22:40:08] 绅士 5R/0Z, 队列 3R/0D
[Aug 18 22:40:08] 绅士-scan-1 GET https://exhentai.org/s/090c6e2e58/792572-8 200 3885
[Aug 18 22:40:09] 绅士-scan-1 GET https://exhentai.org/s/43f5303de3/792572-9 200 3891
[Aug 18 22:40:10] 绅士-scan-1 GET https://exhentai.org/s/5d5e85a6f7/792572-10 200 3893
[Aug 18 22:40:10] 绅士-scan-1 GET https://exhentai.org/s/3feb282cd4/792572-11 200 3899
[Aug 18 22:40:10] 绅士-scan-1 GET https://exhentai.org/s/6784eaaf97/792572-12 200 3897
[Aug 18 22:40:11] 绅士-scan-1 GET https://exhentai.org/s/29fd1c8228/792572-13 200 3900
[Aug 18 22:40:11] 绅士-scan-1 GET https://exhentai.org/s/768c5f93da/792572-14 200 3900
[Aug 18 22:40:11] 绅士-scan-1 GET https://exhentai.org/s/5bf26e92e8/792572-15 200 3897
[Aug 18 22:40:12] 绅士-scan-1 GET https://exhentai.org/s/6e1b7f6561/792572-16 200 3898
[Aug 18 22:40:12] 绅士-scan-1 GET https://exhentai.org/s/c38006f3f8/792572-17 200 3899
[Aug 18 22:40:13] 绅士 5R/0Z, 队列 13R/0D
[Aug 18 22:40:14] 绅士-scan-1 GET https://exhentai.org/s/35c277d490/792572-18 200 3898
[Aug 18 22:40:14] 绅士-scan-1 GET https://exhentai.org/s/7144c51e4a/792572-19 200 3899
[Aug 18 22:40:15] 绅士-scan-1 GET https://exhentai.org/s/186845db47/792572-20 200 3896
[Aug 18 22:40:15] 绅士-scan-1 GET https://exhentai.org/s/8ee17cc631/792572-21 200 3896
[Aug 18 22:40:15] 绅士-scan-1 GET https://exhentai.org/s/95d29834fc/792572-22 200 3898
[Aug 18 22:40:16] 绅士-scan-1 GET https://exhentai.org/s/65b152fae6/792572-23 200 3898
[Aug 18 22:40:16] 绅士-down-1 GET http://114.38.118.149:5566/h/db37e70c2ce19affb7b4f2f4278e224d2cefcaf5-645920-1200-1745-jpg/keystamp=1471531800-f47f5379ee/Resource.jpg 200 645920
[Aug 18 22:40:16] 绅士-scan-1 GET https://exhentai.org/s/c9a6a9c98f/792572-24 200 3898
[Aug 18 22:40:16] 图片已下载 #001 Resource.jpg
[Aug 18 22:40:16] 绅士-scan-1 GET https://exhentai.org/s/588bd82ef0/792572-25 200 3898
[Aug 18 22:40:17] 绅士-down-4 GET http://219.79.6.139:38783/h/598cf3fd8fb70f88cbfc6541a0f7f2130a1473ea-697683-1200-1739-jpg/keystamp=1471531800-2c37bc8227/04_003.jpg 200 697683
[Aug 18 22:40:17] 图片已下载 #004 04_003.jpg
[Aug 18 22:40:17] 绅士-scan-1 GET https://exhentai.org/s/5d893a6cef/792572-26 200 3899
[Aug 18 22:40:17] 绅士-scan-1 GET https://exhentai.org/s/3b2652d7d7/792572-27 200 3898
[Aug 18 22:40:17] 绅士-scan-1 GET https://exhentai.org/s/3fb304fb30/792572-28 200 3898
[Aug 18 22:40:18] 绅士-scan-1 GET https://exhentai.org/s/97ef9f68f0/792572-29 200 3899
[Aug 18 22:40:18] 绅士 5R/0Z, 队列 23R/2D
[Aug 18 22:40:19] 绅士-down-1 GET http://106.187.100.179:7426/h/31dc1113191877f32fe6f51e8f15e4b6894ffd63-513174-1200-1744-jpg/keystamp=1471531800-48679f41f2/04_004.jpg 200 513174
[Aug 18 22:40:19] 图片已下载 #005 04_004.jpg
[Aug 18 22:40:22] 绅士-down-1 GET http://219.73.126.25:26985/h/d1766a11bbf093b41d5a33536d2fa035baa65ec2-631285-1200-1750-jpg/keystamp=1471531800-e22a7bf5bf/04_006.jpg 200 631285
[Aug 18 22:40:22] 图片已下载 #007 04_006.jpg
[Aug 18 22:40:23] 绅士 5R/0Z, 队列 21R/4D
[Aug 18 22:40:25] 绅士-down-3 GET http://220.132.85.53:30333/h/2097dc6954de83c12387c25133a1c5c0920bf97e-524869-1200-1743-jpg/keystamp=1471531800-4f7e2cf6a2/04_002.jpg 200 524869
[Aug 18 22:40:25] 图片已下载 #003 04_002.jpg
[Aug 18 22:40:26] 绅士-down-4 GET http://103.241.61.30:8445/h/7294c6c826615d77d69db9266bf3627e62ff0d90-526127-1200-1740-jpg/keystamp=1471531800-a7165bc7e8/04_005.jpg 200 526127
[Aug 18 22:40:26] 图片已下载 #006 04_005.jpg
[Aug 18 22:40:26] 绅士-down-1 GET http://211.33.159.243:56133/h/737a98935d6e541de6faf91e6f3d101088948c7e-611809-1200-1742-jpg/keystamp=1471531800-705af653ea/04_007.jpg 200 611809
[Aug 18 22:40:27] 图片已下载 #008 04_007.jpg
[Aug 18 22:40:28] 绅士 5R/0Z, 队列 18R/7D
[Aug 18 22:40:29] 绅士-down-4 GET http://219.79.6.139:38783/h/134b6d234190a5db8c89c4a3cec70d87b887eeeb-573538-1200-1748-jpg/keystamp=1471531800-2ea2ad80c1/04_009.jpg 200 573538
[Aug 18 22:40:29] 图片已下载 #010 04_009.jpg
[Aug 18 22:40:33] 绅士-down-2 GET http://220.134.105.102:3015/h/27fa150137624e23485f2da1c49b56788432ce55-636819-1200-1745-jpg/keystamp=1471531800-499799683e/04_001.jpg 200 636819
[Aug 18 22:40:33] 图片已下载 #002 04_001.jpg
[Aug 18 22:40:33] 绅士-down-4 GET http://219.79.6.139:38783/h/06949e0e79bea73cec2f6d408d8c7f27d9296ee6-489990-1200-1744-jpg/keystamp=1471531800-c9efbb92d4/04_011.jpg 200 489990
[Aug 18 22:40:33] 图片已下载 #012 04_011.jpg
[Aug 18 22:40:33] 绅士 5R/0Z, 队列 15R/10D
[Aug 18 22:40:33] 绅士-down-3 GET http://59.124.168.175:10164/h/27006d811f5b5ec05e9a5217b202d7b2732f7cc8-546482-1200-1752-jpg/keystamp=1471531800-a093e425a9/04_008.jpg 200 546482
[Aug 18 22:40:33] 图片已下载 #009 04_008.jpg
[Aug 18 22:40:37] 绅士-down-1 GET http://112.118.80.252:63369/h/7878829e0003100623dc7df331f505a234c7eae5-583723-1200-1752-jpg/keystamp=1471531800-c7715ea423/04_010.jpg 200 583723
[Aug 18 22:40:37] 图片已下载 #011 04_010.jpg
[Aug 18 22:40:38] 绅士 5R/0Z, 队列 13R/12D
[Aug 18 22:40:41] 绅士-down-1 GET http://125.143.18.86:56133/h/1756824208fd2f1fa33ae8919b16dec478ea48b5-544085-1200-1747-jpg/keystamp=1471531800-28fcca893f/04_015.jpg 200 544085
[Aug 18 22:40:41] 图片已下载 #016 04_015.jpg
[Aug 18 22:40:43] 绅士-down-4 GET http://114.199.146.177:27999/h/961cf5600b8db4ea8b0433110da50235be0f3fc4-626230-1200-1749-jpg/keystamp=1471531800-7fa1e657df/04_013.jpg 200 626230
[Aug 18 22:40:43] 图片已下载 #014 04_013.jpg
[Aug 18 22:40:43] 绅士 5R/0Z, 队列 11R/14D
[Aug 18 22:40:43] 绅士-down-2 GET http://114.199.146.177:27999/h/a1df87f6b16b4b331559f42e0f4032ed85039453-598993-1200-1751-jpg/keystamp=1471531800-d621865ca8/04_012.jpg 200 598993
[Aug 18 22:40:43] 图片已下载 #013 04_012.jpg
[Aug 18 22:40:44] 绅士-down-3 GET http://36.234.203.49:4700/h/8eeee65bf9d8b5b42490ca103909575242c1ea9f-524617-1200-1750-jpg/keystamp=1471531800-36b9c4b769/04_014.jpg 200 524617
[Aug 18 22:40:45] 图片已下载 #015 04_014.jpg
[Aug 18 22:40:45] 绅士-down-1 GET http://133.130.123.15:63428/h/2589971683ae336175d13f389ea533328861fa0b-604815-1200-1755-jpg/keystamp=1471531800-447e766307/04_016.jpg 200 604815
[Aug 18 22:40:45] 图片已下载 #017 04_016.jpg
[Aug 18 22:40:48] 绅士 5R/0Z, 队列 8R/17D
[Aug 18 22:40:48] 绅士-down-2 GET http://211.224.54.176:15975/h/531dc11eb656a4500ef137f7ddc1ce2afd0778e1-593823-1200-1753-jpg/keystamp=1471531800-5bf9617c6e/04_018.jpg 200 593823
[Aug 18 22:40:48] 图片已下载 #019 04_018.jpg
[Aug 18 22:40:49] 绅士-down-4 GET http://118.172.1.166:17417/h/230f75d9d3e2af0372e51c53be95b5a452d34677-609153-1200-1751-jpg/keystamp=1471531800-1f64976727/04_017.jpg 200 609153
[Aug 18 22:40:49] 图片已下载 #018 04_017.jpg
[Aug 18 22:40:51] 绅士-down-1 GET http://157.7.53.37:45371/h/de3dce544e1e795ca9d2d3d2f3d0d5516b3b499d-662410-1200-1757-jpg/keystamp=1471531800-a12bb5c04f/04_020.jpg 200 662410
[Aug 18 22:40:51] 图片已下载 #021 04_020.jpg
[Aug 18 22:40:51] 绅士-down-2 GET http://202.83.109.139:8089/h/bac923e726c6cb1608d301411e78b507b11cc4c6-623158-1200-1754-jpg/keystamp=1471531800-f420b0e553/04_021.jpg 200 623158
[Aug 18 22:40:51] 图片已下载 #022 04_021.jpg
[Aug 18 22:40:52] 绅士-down-3 GET http://157.7.53.38:45371/h/aab4cd7aea0a8c92608a37e1967dcc8a2dbe9b81-594409-1200-1751-jpg/keystamp=1471531800-0453b10823/04_019.jpg 200 594409
[Aug 18 22:40:52] 图片已下载 #020 04_019.jpg
[Aug 18 22:40:53] 绅士 5R/0Z, 队列 3R/22D
[Aug 18 22:40:57] 绅士-down-3 GET http://112.118.80.252:63369/h/1f57ef8673ba566143e693cc30545defd7c9d0ac-672679-1200-1751-jpg/keystamp=1471531800-99c8d5189e/04_025.jpg 200 672679
[Aug 18 22:40:57] 图片已下载 #026 04_025.jpg
[Aug 18 22:40:57] 绅士-down-4 GET http://114.36.45.171:60000/h/ef988a70b779d782825de98710f0c39b551b11c5-547958-1200-1753-jpg/keystamp=1471531800-a747681ccd/04_022.jpg 200 547958
[Aug 18 22:40:57] 图片已下载 #023 04_022.jpg
[Aug 18 22:40:57] 绅士-down-1 GET http://118.142.224.206:19795/h/b9721da723f36eed9e91aeba9b75a66176e45c72-663747-1200-1752-jpg/keystamp=1471531800-1f7091d1bc/04_023.jpg 200 663747
[Aug 18 22:40:57] 图片已下载 #024 04_023.jpg
[Aug 18 22:40:57] 绅士-down-4 GET http://202.83.109.139:8089/h/960bbe9572b9e1c9e8a79e071c47048e67901663-695374-1200-1754-jpg/keystamp=1471531800-399986fa2b/04_027.jpg 404 28
[Aug 18 22:40:57] 图片已下载 #028 04_027.jpg
[Aug 18 22:40:58] 绅士 5R/0Z, 队列 0R/26D
[Aug 18 22:41:01] 绅士-down-2 GET http://183.88.136.80:34344/h/560d9a8158fab0dcbaa30eec6c41eb83ec7589ce-686455-1200-1755-jpg/keystamp=1471531800-4705dd81d7/04_024.jpg 200 686455
[Aug 18 22:41:01] 图片已下载 #025 04_024.jpg
[Aug 18 22:41:03] 绅士 5R/0Z, 队列 0R/27D
[Aug 18 22:41:09] 绅士 5R/0Z, 队列 0R/27D
[Aug 18 22:41:10] 绅士-down-3 GET http://114.35.122.30:50000/h/dbb52c31a23d17b522a1030d280d334c8e7ae7da-671617-1200-1760-jpg/keystamp=1471531800-85ab80c893/04_026.jpg 200 671617
[Aug 18 22:41:10] 图片已下载 #027 04_026.jpg
[Aug 18 22:41:10] 绅士-down-1 GET http://122.116.42.192:12300/h/9b03e85c75d42c9971a794123a30d4ef6c156785-692755-1200-1763-jpg/keystamp=1471531800-8506617940/04_028.jpg 200 692755
[Aug 18 22:41:10] 图片已下载 #029 04_028.jpg
[Aug 18 22:41:10] t-down-1 exit
[Aug 18 22:41:10] t-down-4 exit
[Aug 18 22:41:11] t-down-3 exit
[Aug 18 22:41:11] t-scan-1 exit
[Aug 18 22:41:11] t-down-2 exit
[Aug 18 22:41:12] 任务 #a84c6366 下载完成

**Comment by fffonion** [comment]
哦我知道了我去改一下

**Comment by freeocha** [comment]
谢谢大大
P.S.  因为上面这个log留着有点危险，我5分钟以后就删了

**Comment by fffonion** [comment]
现在就删吧，我看好了

**Comment by fffonion** [comment]
试试这个版本？
[xeHentai-2.0.1.0.exe.zip](https://github.com/fffonion/xeHentai/files/425337/xeHentai-2.0.1.0.exe.zip)

**Comment by freeocha** [comment]
没有问题，应该说很强大，非常感谢大大！
我特地找了一个900多页的cg测试，终于碰到了404，然而变了僵尸的线程很快就恢复了，最后所有页面都成功加载
