### ISSUE TITLE
发生错误: list index out of range

### ISSUE THREAD

**Issue by wialny** [fffonion/xeHentai#23]
[Aug 28 02:26:36] xeHentai 2.011 已启动
[Aug 28 02:26:38] 任务 #a9029d53 开始
[Aug 28 02:26:40] 任务 #a9029d53 发生错误: list index out of range
[Aug 28 02:26:40] 程序循环已完成

File Size:	1.84 GB
Length:	1528 pages

**Comment by fffonion** [comment]
`log_verbose`设成3，然后日志贴下

**Comment by wialny** [comment]
[Aug 28 02:30:30] xeHentai 2.011 已启动
[Aug 28 02:30:40] cfg {'username': None, 'verbose': 3, 'log_verbose': 3, 'log_path': 'eh.log', 'rpc_secret': None, 'download_thread_cnt': 5, 'cookie': None, 'proxy': None, 'key': None, 'download_ori': False, 'scan_thread_cnt': 1, 'rename_ori': False, 'rpc_interface': 'localhost', 'daemon': False, 'logpath': 'E:\\e-hentai\\eh.log', 'archive': False, 'save_tasks': False, 'urls': ['https://exhentai.org/g/969963/e826dc09e8/'], 'make_archive': False, 'rpc_port': None, 'dir': 'E:\\e-hentai', 'interactive': True}
[Aug 28 02:30:40] 任务 #846768ed 开始
[Aug 28 02:30:41] 绅士-main GET https://exhentai.org/g/969963/e826dc09e8/ 200 33995
[Aug 28 02:30:41] 任务 #846768ed 发生错误: list index out of range
[Aug 28 02:30:41] 程序循环已完成

**Comment by fffonion** [comment]
2.0.1.3已修复：）

**Comment by wialny** [comment]
谢谢! 辛苦了
