### ISSUE TITLE
无法登录 warning：list index out of range

### ISSUE THREAD

**Issue by lin710839742** [fffonion/xeHentai#24]
输入用户名密码后无法登录
中间输出是Warning：list index out of range
我手动拷贝了老版本的cookie进来，就可以正常使用了
尝试了2.010到2.013均是如此
用户名12位，密码11位

**Comment by lin710839742** [comment]
Traceback (most recent call last):
  File "<string>", line 430, in <module>
  File "<string>", line 110, in mkcookie
IndexError: list index out of range
然后我发现老版本删掉cookie后也登录不上去了，这个是1.5.4.9991的报错

**Comment by fffonion** [comment]
用户名密码是否有除了英文数字以外的字符？

**Comment by lin710839742** [comment]
嗯，我一开始也是这么想的。不过并没有，只有英文和数字。然后我还特地新注册了个测试账户，账号密码都是最简单的字母，也不行。

**Comment by fffonion** [comment]
testexhentai
hentai
这个可以登录不

**Comment by lin710839742** [comment]
可以了，而且我试了试，之前的问题不会出现了。我用自己账号登录成功了。
想了想，所做的改动只有刚在这台PC上搭好SS，是开了系统代理的关系吗？
然后我把SS关掉了。发现也登录成功了。
之前100%复现的问题无法复现了，有点迷= =
不管怎样，是好消息，多谢老司机。

**Comment by fffonion** [comment]
有可能，顺便你可以直接在`config.py`里设置代理
`proxies=["socks5://127.0.0.1:1080"]`
