### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by xhzz161** [fffonion/xeHentai#25]
![qq 20160902023053](https://cloud.githubusercontent.com/assets/21747275/18194677/5a915880-70b5-11e6-879a-218f30cf48df.png)

INFO - [14:29:41] xeHentai 2.013 已启动
当前没有登陆，要登陆吗 (y/n)? > y
输入用户名 > testexhentai
输入密码   > hentai
DEBG - [14:30:20] 登录绅士
WARN - [14:30:21] list index out of range
INFO - [14:30:21] 无法登录绅士
输入地址（使用,分割下载多个）>

输入地址后因为没有登录会无法下载
之后只能关闭

**Comment by fffonion** [comment]
是否开了不能用的代理？ 可以看下和#23 是否类似

**Comment by xhzz161** [comment]
没有代理 从没用过任何代理 因为不会。。。
看了看#24
我是因为很久没用了 这次打开老版本无法使用 下载就直接关闭
我也没有复制cookie 直接删掉老版本 下了个新版本 结果发现无法登陆
设置代理
proxies = ["socks5://127.0.0.1:1080"] 之后 会变成这样子:


DEBG - [02:51:05] 代理池中有1个代理
INFO - [02:51:05] xeHentai 2.013 已启动
当前没有登陆，要登陆吗 (y/n)? > y
输入用户名 > testexhentai
输入密码   > hentai
DEBG - [02:51:13] 登录绅士
WARN - [02:51:14] 绅士-main POST http://forums.e-hentai.org/index.php?act=Login&CODE=01: SOCKSHTTPConnectionPool(host='forums.e-hentai.org', port=80): Max retries exceeded with url: /index.php?act=Login&CODE=01 (Caused by NewConnectionError('<requests.packages.urllib3.contrib.socks.SOCKSConnection object at 0x03166230>: Failed to establish a new connection: [Errno 10061] ',))
WARN - [02:51:16] 绅士-main POST http://forums.e-hentai.org/index.php?act=Login&CODE=01: SOCKSHTTPConnectionPool(host='forums.e-hentai.org', port=80): Max retries exceeded with url: /index.php?act=Login&CODE=01 (Caused by NewConnectionError('<requests.packages.urllib3.contrib.socks.SOCKSConnection object at 0x03166490>: Failed to establish a new connection: [Errno 10061] ',))
WARN - [02:51:18] 绅士-main POST http://forums.e-hentai.org/index.php?act=Login&CODE=01: SOCKSHTTPConnectionPool(host='forums.e-hentai.org', port=80): Max retries exceeded with url: /index.php?act=Login&CODE=01 (Caused by NewConnectionError('<requests.packages.urllib3.contrib.socks.SOCKSConnection object at 0x03166570>: Failed to establish a new connection: [Errno 10061] ',))
WARN - [02:51:20] 绅士-main POST http://forums.e-hentai.org/index.php?act=Login&CODE=01: SOCKSHTTPConnectionPool(host='forums.e-hentai.org', port=80): Max retries exceeded with url: /index.php?act=Login&CODE=01 (Caused by NewConnectionError('<requests.packages.urllib3.contrib.socks.SOCKSConnection object at 0x03166650>: Failed to establish a new connection: [Errno 10061] ',))
WARN - [02:51:23] 绅士-main POST http://forums.e-hentai.org/index.php?act=Login&CODE=01: SOCKSHTTPConnectionPool(host='forums.e-hentai.org', port=80): Max retries exceeded with url: /index.php?act=Login&CODE=01 (Caused by NewConnectionError('<requests.packages.urllib3.contrib.socks.SOCKSConnection object at 0x03166730>: Failed to establish a new connection: [Errno 10061] ',))
Traceback (most recent call last):
  File "xeH.py", line 5, in <module>
  File "xeHentai\cli.py", line 45, in start
  File "xeHentai\cli.py", line 57, in main
  File "xeHentai\cli.py", line 159, in interactive
  File "xeHentai\core.py", line 433, in login_exhentai
  File "xeHentai\worker.py", line 47, in request
  File "xeHentai\proxy.py", line 38, in proxied_request
xeHentai.proxy.PoolException: try to use proxy but no proxies avaliable
Failed to execute script xeH
请按任意键继续. . .

**Comment by xhzz161** [comment]
参考#23
更改log_verbose设成3 之后也不行


VERB - [02:54:14] cfg {'username': None, 'verbose': 3, 'log_verbose': 3, 'log_path': 'eh.log', 'rpc_secret': None, 'download_thread_cnt': 5, 'cookie': None, 'proxy': None, 'key': None, 'download_ori': False, 'scan_thread_cnt': 1, 'rename_ori': False, 'rpc_interface': 'localhost', 'daemon': False, 'logpath': u'G:\\xeHentai-2.0.1.3\\eh.log', 'archive': False, 'save_tasks': False, 'urls': [], 'make_archive': False, 'rpc_port': None, 'dir': u'G:\\xeHentai-2.0.1.3', 'interactive': True}
INFO - [02:54:14] xeHentai 2.013 已启动
当前没有登陆，要登陆吗 (y/n)? > y
输入用户名 > testexhentai
输入密码   > hentai
DEBG - [02:54:22] 登录绅士
VERB - [02:54:23] 绅士-main POST http://forums.e-hentai.org/index.php?act=Login&CODE=01 200 11604
WARN - [02:54:23] list index out of range
INFO - [02:54:23] 无法登录绅士
输入地址（使用,分割下载多个）>

**Comment by fffonion** [comment]
proxies = 还是设成None，因为你1080上并没有代理
我改一下让它显示为啥登录失败好了

**Comment by xhzz161** [comment]
恩 已经改回去了

**Comment by fffonion** [comment]
晚上打包2.0.1.4 😄

**Comment by xhzz161** [comment]
好的好的 -3- 感谢

**Comment by fffonion** [comment]
done

**Comment by xhzz161** [comment]
感谢感谢 -3-
刚刚下载试了试 
这次显示出了具体错误

INFO - [12:02:23] xeHentai 2.014 已启动
当前没有登陆，要登陆吗 (y/n)? > y
输入用户名 > testexhentai
输入密码   > hentai
DEBG - [12:02:28] 登录绅士
WARN - [12:02:28] The captcha was not entered correctly. Please try again.
INFO - [12:02:28] 无法登录绅士
输入地址（使用,分割下载多个）>

这个captcha怎么搞？

**Comment by fffonion** [comment]
这个是你的ip登录次数太多了所以让你输验证码了。
可以1. 开代理换ip
2. 用浏览器登录然后用rpc模式直接转移cookie

**Comment by xhzz161** [comment]
Orz  都不会用。。

**Comment by fffonion** [comment]
那就等一段时间比如一天再登录

**Comment by xhzz161** [comment]
okok 我等满24小时再试试

**Comment by xhzz161** [comment]
刚刚试了试登陆。。
失败了。。。现实一样的错误。。

**Comment by fffonion** [comment]
在浏览器登录然后用rpc吧
可以看视频教程：https://dl.yooooo.us/share/xeHentai/xeHentai-2.0%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.mp4
