### ISSUE TITLE
most recent call last

### ISSUE THREAD

**Issue by wialny** [fffonion/xeHentai#26]
这个问题并没有影响到图片下载

在最后一张图片下载完成后没有正常结束, 而是抛出了下图的异常:

![image](https://cloud.githubusercontent.com/assets/12374028/18393483/1946b652-76e8-11e6-92eb-f8eae12a6d6b.png)

LOG里最后几行是:

> [Sep09 23:42:49] 绅士-down-4 GET http://37.48.81.90/lid/48229655/0ab42db4ccbf90f4d2b2ade94be8dedd1670c5eb-652942-854-1237-png/3b258678b02604cf49bb03b9119161a7ad5945cd-362644-854-1237-jpg/2400/tzoo4hk8rt3/0176.jpg: HTTPConnectionPool(host='37.48.81.90', port=80): Read timed out.
>[Sep 09 23:42:50] 绅士 6R/0Z, 队列 0R/190D
>[Sep 09 23:42:55] 绅士 6R/0Z, 队列 0R/190D
>[Sep 09 23:43:00] 绅士 6R/0Z, 队列 0R/190D
>[Sep 09 23:43:02] 绅士-down-4 可能变成了丧尸
>[Sep 09 23:43:05] 绅士 5R/1Z, 队列 0R/190

(log最后一行的"0R/190"后面并没有"D")

经确认所有图片都已经下载完成, 
设置全部默认, 没有要重命名.

可能无法重现这个错误

**Comment by fffonion** [comment]
这个重命名是因为下载的时候默认扩展名是jpg，下完之后把它改成真正的格式
不是很懂这个问题出在哪里，总之我加个try再说

**Comment by fffonion** [comment]
https://dl.yooooo.us/share/xeHentai/xeHentai-2.0.1.5.exe.zip

**Comment by wialny** [comment]
@fffonion  谢谢!
