### ISSUE TITLE
程序遇到CEwanted这张图就很容易出错，很奇怪

### ISSUE THREAD

**Issue by freeocha** [fffonion/xeHentai#27]
系统: Win10 (64bit)
程序: 2.0.1.5

已经遇到过这一问题很多次了，哪怕是不一样的连接，只要里面有 CEwanted.jpg 同时下载器出现了僵尸，就很容易出错。删掉这张图，如果删掉 CEwanted.jpg 再运行程序还会遇到以下情况：

[Feb 26 11:59:07] xeHentai 2.015 已启动
[Feb 26 11:59:07] 任务 #2d5c38fd 开始
[Feb 26 11:59:10] 任务 #2d5c38fd 标题
[Feb 26 11:59:10] 任务 #2d5c38fd 将下载6个文件，共108个 
[Feb 26 11:59:13] 图片已下载 #3 CE_1164_002.jpg
[Feb 26 11:59:14] 图片已下载 #8 CEwanted.jpg
[Feb 26 11:59:14] 图片已下载 #73 CE_1164_072.jpg
[Feb 26 11:59:15] 绅士 4R/0Z, 队列 3R/108D
[Feb 26 11:59:15] 图片已下载 #8 CEwanted.jpg
[Feb 26 11:59:15] 图片已下载 #8 CEwanted.jpg
[Feb 26 11:59:16] 图片已下载 #8 CEwanted.jpg
[Feb 26 11:59:20] 绅士 1R/0Z, 队列 3R/108D
[Feb 26 11:59:21] 图片已下载 #8 CE_1164_007.jpg
[Feb 26 11:59:21] 任务 #2d5c38fd 下载完成
[Feb 26 11:59:22] 程序循环已完成

**Comment by fffonion** [comment]
这个问题应该已经修复了，可以试下最新版本2.0.1.7
不行的话贴个图册地址我试试

**Comment by freeocha** [comment]
刚用2.0.1.7试了同一个连接没有问题，应该是好了

谢谢fffonion 大大
