### ISSUE TITLE
要是中斷程序再開後下載同一個畫廊，先前下載成功的檔案不會改名

### ISSUE THREAD

**Issue by n40355** [fffonion/xeHentai#28]
系统: Win7 (64bit)
程序: 2.0.1.5&2.0.1.7
例如下載一個畫廊，可是達到限額或其他原因關掉之後，再重開程式並下載同個畫廊，下載完改名只會改後面這次下載的部分，先前成功下載的部分就依然還是預設的編號擋名。
另外大大有打算增加畫廊裡的小範圍下載嗎? 就是1000張圖中，只下載第500張到第900張之間的圖這樣。
還是這些功能都有只是我沒設定好@@
不好意思打擾了

**Comment by fffonion** [comment]
第一个不会改名的问题是这样的，需要把配置里的save_tasks改成=True才可以在中断下载之后重命名所有文件
第二个确实是没有，我过段时间加上 :smile:

**Comment by n40355** [comment]
謝謝你撥空回覆
這樣看來已經下完的只能重載或手動改了Orz
期待新功能，加油

**Comment by Aniark** [comment]
在遇到不可抗力（如配额不足）必须中断下载时，除了楼上说的将s_t
改成True以外，还必须使用ctrl+c中断本次下载，下次继续下载时才能重新命名

**Comment by fffonion** [comment]
已更新2.018，可使用download_range指定下载范围：）

**Comment by Aniark** [comment]
@fffonion 我看release版本号是2.0.1.7？

**Comment by fffonion** [comment]
测试完成前可以先来这里下载
https://dl.yooooo.us/share/xeHentai/?1
