### ISSUE TITLE
漫画文件夹命名问题

### ISSUE THREAD

**Issue by telessa** [fffonion/xeHentai#29]
https://e-hentai.org/g/134212/102460125f/
[大暮維人]Peter Pan Syndrome (Chinese)
[中文]

[大暮維人]Peter Pan Syndrome (Chinese)
Roman Script
Uploader:	[大暮維人]Peter Pan Syndrome (Chinese)
	New	
	Blank Vote
Japanese Script
Uploader:	[中文]
	New	
	Blank Vote

默认下载的是日文名称 而不是标题显示的罗马音
然后就出现了奇怪的问题 漫画名 中文
怎么改成以罗马音下载呢？

**Comment by fffonion** [comment]
已更新2.018，可设置`jpn_title=False`使用罗马音

**Comment by telessa** [comment]
非常感谢
