### ISSUE TITLE
表站url可能改版了，需要改正则

### ISSUE THREAD

**Issue by lxyunclebill** [fffonion/xeHentai#30]
现在表站是https://e-hentai.org/XXXXXXXX，core.py 116 行的正则
^https*://(g\.e\-|ex)hentai\.org/[^/]+/\d+/[^/]+/*#*$
可能要改为
^https*://(g\.e\-|e\-|ex)hentai\.org/[^/]+/\d+/[^/]+/*#*$

**Comment by fffonion** [comment]
你大概用的老的版本？
https://github.com/fffonion/xeHentai/blob/master/xeHentai/core.py#L116
