### ISSUE TITLE
一种图片下载失败的情况

### ISSUE THREAD

**Issue by xoxo1984** [fffonion/xeHentai#31]
使用时发现一种图片下载失败的情况，此时图片如[此图](https://user-images.githubusercontent.com/27839118/32261427-65ae6944-bf09-11e7-9ce6-aaff7ae2c20a.jpg)所示，且大小也和网页上提示的大小不一致

建议增加图片大小检查功能 - 在下载图片前先记录图片大小，下载完成后检查实际大小是否和记录一致，不一致则重新下载

根据是否下载原图，可以有两种记录方式
原图   - 网页上显示"Download original 1200 x 1758 904.5 KB source"中的大小，注意:提示的文件大小是四舍五入的(实际大小926194字节)
非原图 - header中Content-Length的值

**Comment by fffonion** [comment]
试试新版？
https://dl.yooooo.us/share/xeHentai/xeHentai-2.0.1.8.exe.zip

**Comment by xoxo1984** [comment]
新版没有遇到过类似问题了（但我测试得少，不太确认）
另外，自己试了下才发现原图也能取Content-Length，之前的建议好蠢啊……

**Comment by fffonion** [comment]
content-length和实际下载如果不符的话requests应该是会报错的，所以既然下载到了残缺的图可能是
- 镜像存的文件本来就是坏的，所以content-length也是错的，之前这个提交是解决这个问题
- 某个没有考虑的情况下，出错的下载没有被重试

我觉得应该是前一种，你方便的话可以把`log_level`调到3看是否有"下载的图有猫饼"，说明有第一种情况发生

**Comment by xoxo1984** [comment]
突然想起来，图片“断裂”可能是由于超时造成
以前我程序里曾把线程里timeout设得很短，又没检查下载下来的图，很多图都是这样坏的
现在我用进程，且没设timeout，就没有遇到过图片断裂，直到我刚才某次手动中断

**Comment by fffonion** [comment]
我配置里加个timeout的选项

**Comment by fffonion** [comment]
已更新https://s.yooooo.us/u/xeHentai/xeHentai-2.0.1.8.exe.zip
（因为和#32 重复了，timeout的后续问题，可以去#32 这里讨论
