### ISSUE TITLE
图片下载失败 扣流量飞快

### ISSUE THREAD

**Issue by telessa** [fffonion/xeHentai#32]
选择下载原图
看日志 似乎有张图片下载失败（提示有猫饼） 
之后反复要求新地址 要求新地址下载 一次扣6点
扣了1万多看图流量 然而还是失败 只能手动停止（中间我喝茶去了）
这是该怎么解决？

**Comment by fffonion** [comment]
给个地址我试试

**Comment by telessa** [comment]
[Nov 06 22:56:54] t-down-5 vote:1012
[Nov 06 22:56:57] 绅士-scan-1 GET https://e-hentai.org/s/007549587e/253599-2?nl=21959-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438 200 4091
[Nov 06 22:57:02] 绅士-down-1 GET https://e-hentai.org/fullimg.php?gid=253599&page=126&key=ql9tygv8zn2: HTTPConnectionPool(host='37.48.124.86', port=80): Read timed out.
[Nov 06 22:57:05] 绅士-down-4 GET https://e-hentai.org/fullimg.php?gid=253599&page=128&key=my81n258zn2: HTTPConnectionPool(host='37.48.124.86', port=80): Read timed out.
[Nov 06 22:57:16] 绅士-down-5 GET https://e-hentai.org/fullimg.php?gid=253599&page=2&key=jg2xqv88zn2: HTTPConnectionPool(host='46.166.148.137', port=80): Read timed out.
[Nov 06 22:57:31] 绅士-down-4 GET https://e-hentai.org/fullimg.php?gid=253599&page=128&key=my81n258zn2: HTTPConnectionPool(host='37.48.124.86', port=80): Read timed out.
[Nov 06 22:57:33] 绅士-down-1 GET https://e-hentai.org/fullimg.php?gid=253599&page=126&key=ql9tygv8zn2 200 155010
[Nov 06 22:57:33] 绅士-down-1 下载图片时出错: 下载的图片有猫饼, 将在稍后重试
[Nov 06 22:57:33] t-down-1 vote:1012
[Nov 06 22:57:34] 绅士-down-5 GET https://e-hentai.org/fullimg.php?gid=253599&page=2&key=jg2xqv88zn2: HTTPConnectionPool(host='46.166.148.137', port=80): Read timed out.
[Nov 06 22:57:38] 绅士-scan-1 GET https://e-hentai.org/s/96c5d028bd/253599-126?nl=8244-419438&nl=316-419438&nl=318-419438&nl=316-419438&nl=318-419438&nl=316-419438&nl=318-419438&nl=316-419438&nl=318-419438&nl=316-419438&nl=318-419438&nl=316-419438&nl=318-419438&nl=316-419438&nl=318-419438&nl=316-419438&nl=318-419438&nl=316-419438&nl=318-419438&nl=316-419438&nl=318-419438&nl=316-419438&nl=318-419438&nl=316-419438&nl=318-419438&nl=316-419438&nl=318-419438 200 4118
[Nov 06 22:58:00] 绅士-down-4 GET https://e-hentai.org/fullimg.php?gid=253599&page=128&key=my81n258zn2 200 157834
[Nov 06 22:58:00] 绅士-down-4 下载图片时出错: 下载的图片有猫饼, 将在稍后重试
[Nov 06 22:58:00] t-down-4 vote:1012
[Nov 06 22:58:00] 绅士-down-5 GET https://e-hentai.org/fullimg.php?gid=253599&page=2&key=jg2xqv88zn2: HTTPConnectionPool(host='46.166.148.137', port=80): Read timed out.
[Nov 06 22:58:02] 绅士-down-5 下载图片时出错: 连接有问题？, 将在稍后重试
[Nov 06 22:58:02] t-down-5 vote:1009
[Nov 06 22:58:02] 绅士-scan-1 GET https://e-hentai.org/s/fb089c1b83/253599-128?nl=26043-419438&nl=315-419438&nl=318-419438&nl=315-419438&nl=318-419438&nl=315-419438&nl=318-419438&nl=315-419438&nl=318-419438&nl=315-419438&nl=318-419438&nl=315-419438&nl=318-419438&nl=315-419438&nl=318-419438&nl=315-419438&nl=318-419438&nl=315-419438&nl=318-419438&nl=315-419438&nl=318-419438&nl=315-419438&nl=318-419438&nl=315-419438&nl=318-419438&nl=315-419438&nl=318-419438&nl=315-419438 200 4118
[Nov 06 22:58:03] 绅士-scan-1 GET https://e-hentai.org/s/007549587e/253599-2?nl=21959-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438&nl=317-419438&nl=318-419438 200 4091
[Nov 06 22:58:13] 绅士-down-2 GET https://e-hentai.org/fullimg.php?gid=253599&page=128&key=my81n258zn2: HTTPSConnectionPool(host='e-hentai.org', port=443): Read timed out. (read timeout=10)
[Nov 06 22:58:15] 绅士-down-1 GET https://e-hentai.org/fullimg.php?gid=253599&page=126&key=ql9tygv8zn2: HTTPConnectionPool(host='37.48.124.86', port=80): Read timed out.
[Nov 06 22:58:18] 绅士-down-5 GET https://e-hentai.org/fullimg.php?gid=253599&page=2&key=jg2xqv88zn2: HTTPConnectionPool(host='46.166.148.137', port=80): Read timed out.
[Nov 06 22:58:34] 绅士-down-5 GET https://e-hentai.org/fullimg.php?gid=253599&page=2&key=jg2xqv88zn2: HTTPConnectionPool(host='46.166.148.137', port=80): Read timed out.
[Nov 06 22:58:41] 绅士-down-1 GET https://e-hentai.org/fullimg.php?gid=253599&page=126&key=ql9tygv8zn2: HTTPConnectionPool(host='37.48.124.86', port=80): Read timed out.
[Nov 06 22:58:50] 绅士-down-2 GET https://e-hentai.org/fullimg.php?gid=253599&page=128&key=my81n258zn2 200 228434
[Nov 06 22:58:50] 绅士-down-2 下载图片时出错: 下载的图片有猫饼, 将在稍后重试

**Comment by fffonion** [comment]
嗯好像是因为网络不太通畅的问题，导致下载原图时都超时了。
我去加个设置timeout的选项好了

这个问题是11月2日更新的版本之后出现的吗？

**Comment by fffonion** [comment]
加上了一个timeout的选项，可以在`config.py`里设置
https://s.yooooo.us/u/xeHentai/xeHentai-2.0.1.8.exe.zip?171106

**Comment by telessa** [comment]
是11月2日更新的版本之后出现的

**Comment by telessa** [comment]
非常感谢

**Comment by telessa** [comment]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'setCookie'], params: [[u'ipb_member_id=3710584; ipb_pass_hash=9fbcb58cd648ace044e8e331f4863c0a; s=b3d827ea3; star=1-2a3d9e82f3; hath_perks=m2.m3.a.tf.t1.m1-1e5ccd4330; nw=1; event=1509981453; lv=1510026749-1510031681'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/254017/a241e01a63/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/253799/ae4710c471/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/253792/158cfaf2bb/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/253727/121b3ade39/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/253630/e96355d318/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/253599/826041d3fb/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/253281/022512d819/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/253160/7bc18fe066/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/252970/8a76f81af2/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/252967/26e798d0e0/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/252571/be4fb57897/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/252405/051a0d2cba/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/252313/1b0db14b7d/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/252311/aec83e2964/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/252257/014bc52f13/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/252235/630a82e246/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/251754/e2183ac2bd/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/251646/a06e2e64a4/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/251596/ec598e4029/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/251336/0b2cf965db/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/251287/f5d927e5b0/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/251253/8f2f977f87/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/250982/088e842e30/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/250970/ecf206b02b/'], {}]
[Nov 07 13:21:05] RPC from: 127.0.0.1, cmd: [u'addTask'], params: [[u'https://e-hentai.org/g/250133/5f934ee02b/'], {}]
[Nov 07 13:21:05] 任务 #1ac1c6f7 开始
[Nov 07 13:21:07] 绅士-main GET https://e-hentai.org/g/254017/a241e01a63/ 200 29528
[Nov 07 13:21:08] 绅士-main GET https://e-hentai.org/g/254017/a241e01a63//?p=0 200 29528
[Nov 07 13:21:09] 绅士-main GET https://e-hentai.org/g/254017/a241e01a63//?p=1 200 29779
[Nov 07 13:21:10] 绅士-main GET https://e-hentai.org/g/254017/a241e01a63//?p=2 200 29830
[Nov 07 13:21:12] 绅士-main GET https://e-hentai.org/g/254017/a241e01a63//?p=3 200 29867
[Nov 07 13:21:13] 绅士-main GET https://e-hentai.org/g/254017/a241e01a63//?p=4 200 14013
[Nov 07 13:21:13] state 4 >= 4, bring up montior
[Nov 07 13:21:13] 任务 #1ac1c6f7 标题 [Nanno Koto] Secret Love [Chinese]
[Nov 07 13:21:13] 任务 #1ac1c6f7 将下载0个文件，共161个 
[Nov 07 13:21:13] t-scan-1 start
[Nov 07 13:21:13] t-scan-1 exit
[Nov 07 13:21:17] 绅士 5R/0Z, 队列 0R/161D
[Nov 07 13:21:22] 绅士 5R/0Z, 队列 0R/161D
[Nov 07 13:21:27] 绅士 5R/0Z, 队列 0R/161D
[Nov 07 13:21:32] 绅士 5R/0Z, 队列 0R/161D
[Nov 07 13:21:37] 绅士 5R/0Z, 队列 0R/161D
[Nov 07 13:21:42] 绅士 5R/0Z, 队列 0R/161D
[Nov 07 13:21:43] 绅士-down-5 挂了, 不再理它
[Nov 07 13:21:43] 绅士-down-4 挂了, 不再理它
[Nov 07 13:21:43] 绅士-down-1 挂了, 不再理它
[Nov 07 13:21:43] 绅士-down-3 挂了, 不再理它
[Nov 07 13:21:43] 绅士-down-2 挂了, 不再理它
[Nov 07 13:21:43] 任务 #1ac1c6f7 下载完成

**Comment by telessa** [comment]
还是有点问题
添加一列漫画 其中g/254017 是之前下过的
之后就提示 挂了不再理它 然后停住了 列表中的其他任务 并没有被下载
选择未下载过的 也有这样的提示

**Comment by fffonion** [comment]
OK我修一下
日志里有cookie我把它删掉了

**Comment by telessa** [comment]
非常感谢
