### ISSUE TITLE
希望添加一个“是否使用代理扫描网页”的功能选项

### ISSUE THREAD

**Issue by Aniark** [fffonion/xeHentai#33]
RT，有的代理IP被ex给ban了，无法打开网页；但是可以用代理打开图片
因此希望能用本地IP扫描网页，用代理IP下载图片

**Comment by fffonion** [comment]
好的，有个问题，下载原图的时候需要先请求ex然后获得原图地址，这种情况是应该用代理还是不用代理

**Comment by xoxo1984** [comment]
分两步走咯……
先用本地IP扫描网页获得网页图片的url后
下载该图片（非原图）时不用cookies，用request.get去抓也可以
但这么搞比较麻烦，得重新写模块

**Comment by fffonion** [comment]
@xoxo1984 总之现在开启了`proxy_image_only`之后，请求ex不通过代理 ![10af07c0e296e40f0983e8d6bf6229a2](https://user-images.githubusercontent.com/2135445/32586344-0dfecc80-c4d0-11e7-8084-3953474d8bf9.jpg)

**Comment by Aniark** [comment]
@fffonion 点击“点我开始.bat”报错，尝试用管理员身份运行依旧报错，如下图
![1](https://user-images.githubusercontent.com/10991795/32588358-276de29a-c549-11e7-8e16-e775718c19ce.JPG)

**Comment by fffonion** [comment]
@Aniark 升级了一下requests忘记测试了233
新链接 https://dl.yooooo.us/share/xeHentai/xeHentai-2.0.1.8.exe.zip?171109

**Comment by Aniark** [comment]
@fffonion 这个可以用了，Thank♂ you sir
