### ISSUE TITLE
文件夹里已有的重复下载？

### ISSUE THREAD

**Issue by telessa** [fffonion/xeHentai#36]
手滑删了一部分图 但是有一部分 完整的找回来了
因为可能有丢失 所以试着对几个漫画重下 
发现图片全部重新下载 并且重命名为原名也失效了
单独以序号方式又下了 相当于一个漫画下了两份
试着直接新下一个之前完全没下过的漫画 下第二次 却不会重下
暂停也不会重复已下载 
请问重复图片是怎么检测的?

**Comment by fffonion** [comment]
重复检测只会按照序号检测，如果之前已经重命名成了原名，检测就失效了。这样做是因为有些本子里有重复的原名。

但是程序只会在所有下载均已完成后重命名（和打包）。重命名后，会在文件夹中创建一个`.xehdone`文件，表明当前本子已下完。

**Comment by telessa** [comment]
好的谢谢
