### ISSUE TITLE
疑似下载卡住

### ISSUE THREAD

**Issue by telessa** [fffonion/xeHentai#37]
23日因为有时候网络不稳定 所以
# save tasks to h.json
save_tasks = True
希望之后可以重启再下
24日中午打开发现
[Nov 24 00:56:48] 图片已下载 #259 258.jpg
[Nov 24 00:56:49] 绅士-down-3 GET http://62.112.8.111/im/44f08c4b82c15d347e28a14d0e4421f68473f82e-5542-977-1400-jpg/419848-35ab9808aae339aa999e7b0c87de0334a4aaec75/999.jpg 200 5542
[Nov 24 00:56:49] 图片已下载 #260 999.jpg
[Nov 24 11:09:24] xeHentai 2.018-dev 已启动
[Nov 24 11:09:24] 任务 #c5aaa3d1 开始
[Nov 24 11:09:24] RPC服务器监听在 localhost:8010
可以看到之后的任务完全没动 就这么停了11个小时
第二次重启
[Nov 24 11:35:33] 图片已下载 #257 256.jpg
[Nov 24 11:36:11] 绅士-down-3 GET http://150.95.156.139:51130/h/89d416614a41bab6c2d247583242af08aae8bb93-405527-977-1400-jpg/keystamp=1511494500-8739aee636;fileindex=11706974;xres=org/159.jpg 200 405527
[Nov 24 11:36:11] 图片已下载 #160 159.jpg
[Nov 24 11:44:52] xeHentai 2.018-dev 已启动
[Nov 24 11:44:52] 任务 #c5aaa3d1 开始
[Nov 24 11:44:52] RPC服务器监听在 localhost:8010
[Nov 24 11:44:52] state 4 >= 4, bring up montior
[Nov 24 11:44:52] 任务 #c5aaa3d1 标题 [Fuuga] Kyoushi to Seito to - Teacher and Student [Chinese] [悠月工房]
[Nov 24 11:44:52] 任务 #c5aaa3d1 将下载260个文件，共260个 
同时 这个fuuga的任务是11月24日0：21分已经下过的 我看了图片创建 修改时间也是和eh.log一致

可就是卡住不动 最后一个记录
通常是[Nov 24 11:36:11] 图片已下载 #160 159.jpg
图片已下载 并没有其他的
之后保存任务关掉 就没再出现
请问这是什么情况

**Comment by telessa** [comment]
另 还有一种情况
[Nov 23 03:50:18] t-scan-1 vote:(1009, u'https://e-hentai.org/s/71536505df/42925-96')
[Nov 23 03:50:19] 绅士-scan-1 GET https://e-hentai.org/s/c9e724114e/42925-97 200 188
[Nov 23 03:50:19] 绅士-scan-1 未捕获的异常
Traceback (most recent call last):
  File "xeHentai\worker.py", line 106, in run
  File "xeHentai\worker.py", line 71, in request
  File "xeHentai\filters.py", line 121, in _
  File "xeHentai\filters.py", line 135, in flt_imgurl
IndexError: list index out of range

[Nov 23 03:50:19] t-scan-1 vote:(1009, u'https://e-hentai.org/s/c9e724114e/42925-97')
[Nov 23 03:50:19] 绅士-scan-1 GET https://e-hentai.org/s/fcfc2e8486/42925-98 200 188
[Nov 23 03:50:19] 绅士-scan-1 未捕获的异常
Traceback (most recent call last):
  File "xeHentai\worker.py", line 106, in run
  File "xeHentai\worker.py", line 71, in request
  File "xeHentai\filters.py", line 121, in _
  File "xeHentai\filters.py", line 135, in flt_imgurl
IndexError: list index out of range

[Nov 23 03:50:19] t-scan-1 vote:(1009, u'https://e-hentai.org/s/fcfc2e8486/42925-98')
[Nov 23 03:50:22] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:50:27] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:50:32] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:50:37] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:50:43] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:50:48] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:50:53] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:50:58] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:51:03] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:51:08] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:51:14] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:51:19] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:51:24] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:51:29] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:51:34] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:51:39] 绅士 6R/0Z, 队列 0R/53D
[Nov 23 03:51:39] 任务 #5a50c519 卡住了, 可能是脚本有bug, 或者网络连接太慢了
[Nov 23 11:30:38] xeHentai 2.018-dev 已启动

之前22日 23日（没设置保存任务）卡住时最后一条记录是
任务#卡住了 , 可能是脚本有bug, 或者网络连接太慢了
之后就没了 可以看到这是卡了8个小时 并不像其他的那样很快重试
但是我看这样的记录里也有 正常继续下的 
请问这是什么情况？

**Comment by fffonion** [comment]
后面那个问题应该是我忘记写扫描页面的重试了
![qq 20171124045409](https://user-images.githubusercontent.com/2135445/33195895-9c891854-d0a9-11e7-8a34-61aba02343e1.jpg)

**Comment by fffonion** [comment]
已在2.0.1.9修复：）
