### ISSUE TITLE
RPC模式下下载的问题

### ISSUE THREAD

**Issue by OniityanH** [fffonion/xeHentai#38]

**Comment by OniityanH** [comment]
我exhentai 是上下滚页阅读的，正常输入网址下载没问题，但这样的话RPC会显示说找不到网页，改成普通一页一页的就没有这种问题，请问能改进一下吗

**Comment by fffonion** [comment]
你是说 ex绅士.org/**mpv**/xxx/xxx/ 这样的网址吗，但是应该multipage viewer里木有rpc的链接呀

**Comment by fffonion** [comment]
关闭issue，如有问题请在下面回复
