### ISSUE TITLE
希望添加一个“刷新”的功能

### ISSUE THREAD

**Issue by Aniark** [fffonion/xeHentai#40]
如图所示，在网络状况不佳，甚至突然的断网重连过后，会出现“任务 #xxxxxxx 卡住了, 可能是脚本有bug, 或者网络连接太慢了” 的字样提示

![default](https://user-images.githubusercontent.com/10991795/34327508-80f0dbb6-e901-11e7-8b26-797300193637.JPG)

如果是单个的下载的话，那只需要退出重来一遍就好了
但是如果是多个任务同时进行，那出现这种状况时，因为不知道之前下载到了哪一本了，只能挨个重新复制网址，实在是不方便

因此，希望能像一般的下载工具一样，出现卡住的情况时，暂停任务-继续任务，然后又能恢复下载了。如果xe也能这样，“刷新”任务进度，恢复下载，那能省下很多功夫

**Comment by fffonion** [comment]
这个可能要在webui里做

**Comment by Aniark** [comment]
@fffonion 再反馈一个问题：如上图，界面显示“终止批处理操作吗”，此时不论Y或者N都是关闭该窗口

**Comment by fffonion** [comment]
这行提示是windows给的，没法改变它的行为:smile:

**Comment by fffonion** [comment]
@Aniark 已在webui中实现，请使用https://xehentai.yooooo.us/ 配合2.020以上版本的xehentai使用: )
