### ISSUE TITLE
不明原因大量错误信息

### ISSUE THREAD

**Issue by gamania31610** [fffonion/xeHentai#43]
在部分情况下(不知原因)，在开始下载或下载到一半时，会出现非常大量如图一般的错误信息，但似乎不是某些特定本子的问题，因为重新开启一次获多次后，即可正常下载了

已确定并非网路问题、本子未被移除、IP没有被Ban(网页上可正常浏览)
以及Image Limits是足够的情况下使用

版本为2.019稳定版

![123](https://user-images.githubusercontent.com/24855017/37045928-0fc4a100-21a2-11e8-9c3d-d9db130deb52.jpg)

**Comment by gamania31610** [comment]
对了，版本为2.019稳定版

**Comment by fffonion** [comment]
嗯这个问题我经常可以复现，正在排查中

**Comment by fffonion** [comment]
请尝试2.0.2.0测试版
https://dl.yooooo.us/share/xeHentai/xeHentai-2.0.2.0-%E6%B5%8B%E8%AF%95%E7%89%88.exe.zip
或者
https://dl.yooooo.us/share/xeHentai/xeHentai-2.0.2.0-%E6%B5%8B%E8%AF%95%E7%89%88.split.zip

**Comment by gamania31610** [comment]
有时会出现这信息，之后就不会有任何反应了，不论是完成任务或是尚未完成，而未完成的有时会继续下载有时又不会
![1](https://user-images.githubusercontent.com/24855017/37416730-8c6243aa-27e9-11e8-9510-ff8dbc0305b4.jpg)

**Comment by fffonion** [comment]
已于2.020正式版中解决，如仍有问题，请重新打开本issue
