### ISSUE TITLE
某些Gallery任务启动时发生NameError

### ISSUE THREAD

**Issue by jacob-cn** [fffonion/xeHentai#44]
![xeh](https://user-images.githubusercontent.com/10020112/37258016-3b3632e6-25ac-11e8-9cda-ca87d2e669e8.JPG)
2.0.18版本
获取画廊信息直接就挂了。
暂时只在/172089/3feac3e584/上面发生了，其他Gallery不会。

**Comment by fffonion** [comment]
请下载2.019及以上版本
