### ISSUE TITLE
save_file中提示 WindowsError: [Error 32]

### ISSUE THREAD

**Issue by telessa** [fffonion/xeHentai#45]
[Mar 29 21:27:09] 任务 #3ad40897 标题 [Yantarou Keno] Toire wa Kirei ni [Chinese]
[Mar 29 21:27:09] 任务 #3ad40897 将下载89个文件，共89个 
[Mar 29 21:27:09] 任务 #575499bf 开始
[Mar 29 21:27:13] 绅士 4R/0Z, 队列 4R/1D
[Mar 29 21:27:18] 绅士 4R/0Z, 队列 9R/8D
[Mar 29 21:27:23] 绅士 4R/0Z, 队列 21R/14D
[Mar 29 21:27:28] 绅士 4R/0Z, 队列 31R/18D
[Mar 29 21:27:33] 绅士 4R/0Z, 队列 40R/24D
[Mar 29 21:27:38] 绅士 4R/0Z, 队列 56R/25D
[Mar 29 21:27:43] 绅士 4R/0Z, 队列 61R/27D
[Mar 29 21:27:48] 绅士 4R/0Z, 队列 61R/27D
[Mar 29 21:27:53] 绅士 4R/0Z, 队列 49R/37D
[Mar 29 21:27:58] 绅士 4R/0Z, 队列 34R/52D
[Mar 29 21:28:03] 绅士 4R/0Z, 队列 24R/62D
[Mar 29 21:28:03] 绅士-down-3 未捕获的异常
Traceback (most recent call last):
  File "xeHentai\worker.py", line 193, in run
  File "xeHentai\worker.py", line 136, in request
  File "xeHentai\filters.py", line 123, in _
  File "xeHentai\filters.py", line 214, in download_file
  File "xeHentai\core.py", line 284, in <lambda>
  File "xeHentai\task.py", line 249, in save_file
WindowsError: [Error 32] 

[Mar 29 21:28:09] 绅士 4R/0Z, 队列 21R/66D
[Mar 29 21:28:14] 绅士 4R/0Z, 队列 15R/72D
[Mar 29 21:28:19] 绅士 4R/0Z, 队列 2R/85D
[Mar 29 21:28:24] 绅士 4R/0Z, 队列 0R/87D
[Mar 29 21:28:25] 绅士-down-2 可能变成了丧尸
[Mar 29 21:28:26] 任务 #3ad40897 下载完成

实际上只下载88个 有问题的第7张 变成了 7.xeh
需要重新下载 才会正常

另外下载卡住
最后一行
[Mar 29 16:35:17] 图片已下载 #195 Leo_Self_01_204.png
[Mar 29 16:35:17] t-down-1 exit
[Mar 29 16:35:17] t-scan-1 exit

或者（这个我找不到那一行了 当时打开 就是只有残缺的日期）
[Mar 29

版本xeHentai-2.0.2.0

**Comment by fffonion** [comment]
已于2.020正式版中解决，如仍有问题，请重新打开本issue
