### ISSUE TITLE
小白代理设置问题

### ISSUE THREAD

**Issue by telessa** [fffonion/xeHentai#46]
eh下图 网络不稳定
用的Vultr 和 shadowsocks R
shadowsocks R 用的pac模式
然后
[Apr 22 22:02:52] 绅士-down-1 GET http://62.112.8.132/im/3946192ffb2b3d0c5d83530d2a4bb255ffd97ce1-432064-1998-1370-jpg/423446-d64223fde562cb02df198805a1c381f38f1b81f6/ELLE_030_Cover.jpg?dl=1: SOCKSHTTPConnectionPool(host='62.112.8.132', port=80): Max retries exceeded with url: /im/3946192ffb2b3d0c5d83530d2a4bb255ffd97ce1-432064-1998-1370-jpg/423446-d64223fde562cb02df198805a1c381f38f1b81f6/ELLE_030_Cover.jpg?dl=1 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x058C6730>: Failed to establish a new connection: [Errno 10061] ',))

都是这些

之后改用全局又能下了 而且很快 
但不知道如何确定是代理的效果 平时只是不稳定而已 是能连的（关了代理测试速度比较好？）

**Comment by telessa** [comment]
另外 在全局代理下 
已下载的漫画 会被重新下载
但是关闭代理后 就不会 这是什么问题？

**Comment by fffonion** [comment]
可以设置`proxy_image_only = True`，这样只用代理下载图片，不用代理扫描网页。

重新下载的问题可能和代理没有关系，尝试一下关闭重命名，修改`rename_ori = False`

**Comment by telessa** [comment]
这个确定是关闭的 
rename_ori = False
