### ISSUE TITLE
文件名最后为句号"."结尾的无法正常下载

### ISSUE THREAD

**Issue by chacha1995** [fffonion/xeHentai#48]
原因应该是文件夹无法以.结尾，所以没有正常生成文件夹
另外经常出现任务卡一张图片不断跳黄字WARN，直接点进去图片可以正常读取，或者直接X掉重新开始任务那张图片也可以正常下载完成任务。。。不知道什么问题

**Comment by fffonion** [comment]
emm，是windows吗？

**Comment by chacha1995** [comment]
是的，win7

**Comment by fffonion** [comment]
Fixed in https://github.com/fffonion/xeHentai/commit/5976915cd4a57620eb3a0392166296a4d1020ccc#diff-fbfb28e58a5d207c61759201a0f8a960
