### ISSUE TITLE
想问一下这个下载器的原理？

### ISSUE THREAD

**Issue by liuhan907** [fffonion/xeHentai#49]
我最近在写一个新的下载工具给自己用，以配合我自己的另一个图片管理工具。有几个问题想询问一下：

1.  下载图片是直接获取HTML然后从中分析图片URL，还是说有别的办法。我看到选项中有下载原图的选项，这个和网站页面直接打开看的区别是什么呢？
2.  登陆时需要哪些Cookies呢，我使用工具查看发现有多个Cookies，全部都需要使用么？

我对于Python不是很熟悉，所以想询问以上两个问题，谢谢。

**Comment by fffonion** [comment]
1. 下载图片是从html中分析图片url，如果用户设置了`download_ori = True`，则选择原图链接下载。原图链接是没有被网站压缩过的图片，收有些设定集的时候可能需要。
2. ipb_开头的那些就可以登陆，其他的都是浏览器设置

**Comment by liuhan907** [comment]
明白了，谢谢。
