### ISSUE TITLE
openwrt上运行时出现错误信息

### ISSUE THREAD

**Issue by chr09670** [fffonion/xeHentai#50]
在newifi d2上的openwrt 18.06.1运行时，只能用交互模式下载，并且在每个任务开始时会提示
![default](https://user-images.githubusercontent.com/39577375/47517387-9cbdc800-d8ba-11e8-9521-b0e4d3c63f5e.png)
然而并不影响下载。不过最终不会提示下载完成，只能Ctrl+C结束任务

**Comment by fffonion** [comment]
emm，感觉是个bug，可以尝试设置一下环境变量
```shell
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by fffonion** [comment]
![440b528c3d3f085f941ab7a1c8fdc41f](https://user-images.githubusercontent.com/2135445/47940949-8f4fa180-dea9-11e8-9650-a5f557f1aba2.jpg)
