### ISSUE TITLE
无法登陆，但是能用rpc下exh上的本子

### ISSUE THREAD

**Issue by umf3874** [fffonion/xeHentai#56]
在交互式界面登陆的时候好像连接不上
![pic](https://user-images.githubusercontent.com/37065333/51266777-13b8b780-19f7-11e9-8d03-c78d68dcf648.png)

但是浏览器进exh可以用rpc下载，这个要怎么解决。。

**Comment by fffonion** [comment]
这个是登录页被墙了，你可以给xehentai设置一个代理

**Comment by umf3874** [comment]
今天又试了一下结果打开交互式界面的时候直接是登录状态了，神秘
可能是未登录的时候使用RPC会进入登录状态？

**Comment by fffonion** [comment]
xehentai已自带抗dns污染，可以解决以上问题
如果仍有问题可重开issue或发新issue：）
