### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by kangdenglin** [fffonion/xeHentai#57]
使用windows server R2下载,已经成功登陆exhentai
提示错误 traceback <most recent call last >
xhehntai\core.py
xhehntai\worker.py
xhehntai\filters.py
indexerror list index out of range

**Comment by fffonion** [comment]
请贴一下出错的本子地址，和你的config.py内容

**Comment by fffonion** [comment]
关闭不活跃issue，如果有疑问可以重新打开本issue或开新帖
