### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by caoyanzhang** [fffonion/xeHentai#58]
提个小问题，这个程序我用了一年多，可以清楚的感觉到，在打开主程序后操作程序所在文件夹里的文件时候，选中之后会有卡顿一段时间才能继续操作，而且卡顿时间随着使用时间的增长而越来越长，关掉程序再操作这个文件夹的文件就不卡顿。刚刚找到原因发现是eh.log太大了，有31M，把里面的内容全删了之后就不卡顿了。

**Comment by fffonion** [comment]
这个情况看起来像操作系统的问题，如果安装了实时扫描的杀毒软件，可以设置排除程序文件夹

**Comment by fffonion** [comment]
默认已解决，如果仍有问题可重开issue或发新issue：）
