### ISSUE TITLE
球球你辽救救孩子吧，今天ex更新了，xeHentai Helper插件用不了了

### ISSUE THREAD

**Issue by caoyanzhang** [fffonion/xeHentai#59]
祝开发者大哥福如东海寿比南山早生贵子白头偕老

**Comment by fffonion** [comment]
已更新
![41BB6E48DC0AC213F3A0101125BC6E41](https://user-images.githubusercontent.com/2135445/54627559-ead19480-4a30-11e9-8390-78902c7cac9a.jpg)
