### ISSUE TITLE
网站开启Multi-Page Viewer后爬虫失效

### ISSUE THREAD

**Issue by Dragon-Yu** [fffonion/xeHentai#61]
在用户账号在开启了Multi-Page Viewer后，galley界面下缩略图的超链接会从
形如https://e-hentai.org/s/89a73d841c/1415966-1
变为https://exhentai.org/mpv/1415966/d53b81ce0d/#page1
从而使爬虫失效。
更改函数flt_pageurl中的正则匹配后发现现有程序无法对多页浏览模式下的页面进行爬取。希望作者进行更新或者细化错误提示。

**Comment by fffonion** [comment]
感谢反馈，已更新测试版，可checkout dev分支测试

**Comment by Dragon-Yu** [comment]
> 感谢反馈，已更新测试版，可checkout dev分支测试

使用image_list的数据来爬真是太妙了，但测试版似乎有点bug，已发pr。

**Comment by fffonion** [comment]
问题已解决，现在关闭issue，如有问题可以重新打开
