### ISSUE TITLE
似乎是编码方式的问题？

### ISSUE THREAD

**Issue by zzlg-git** [fffonion/xeHentai#63]
![qt](https://user-images.githubusercontent.com/48383670/61384489-462e6900-a8e3-11e9-88a9-d5e823cede20.jpg)

出现了这样的问题。
可能是・这个符号的问题？因为其他的都能正常下载，包括含有☆符号的。
网址 /g/1441510/0a27121920/

**Comment by fffonion** [comment]
修好了，python3.5 处理无法解码的字符和3.6以上不太一样
![QQ图片20190804020631](https://user-images.githubusercontent.com/2135445/62418220-6cf5da80-b619-11e9-9622-ed1b7e257a19.png)

**Comment by fffonion** [comment]
关闭不活动issue，如有问题请重新打开：）
