### ISSUE TITLE
KeyError: 'down-1'

### ISSUE THREAD

**Issue by neslxzhen** [fffonion/xeHentai#64]
```
Exception in thread monitor9052c328:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "xeHentai\worker.py", line 340, in run
KeyError: 'down-1'
```
![image](https://user-images.githubusercontent.com/33894721/62227056-dbeeeb80-b3ed-11e9-9588-19e463d7310b.png)

download link:
https://e-hentai.org/g/901825/61d6ebecb1/

無法異機還原，這個連結在其他電腦是可以下載的。但這個錯誤偶爾也會出現在下載其他連結的時候

最近因為E站要關了，所以十分緊急，懇請大神協助

**Comment by fffonion** [comment]
日志不太完整，可以看是否是#63这个同一个错误

**Comment by neslxzhen** [comment]
您好 看起來似乎是一樣的，這是無解嗎

**Comment by neslxzhen** [comment]
@fffonion 您好，看起來是一樣的，請問這是無解嗎

**Comment by fffonion** [comment]
有解，我看看怎么修。我先把这个issue关了，有问题可以去#63 集中讨论
