### ISSUE TITLE
UnicodeEncodeError: 'cp950' codec can't encode...

### ISSUE THREAD

**Issue by neslxzhen** [fffonion/xeHentai#65]
```
Exception in thread monitor8c3fc85a:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "xeHentai\worker.py", line 367, in run
  File "xeHentai\task.py", line 326, in rename_fname
UnicodeEncodeError: 'cp950' codec can't encode character u'\ud1a0' in position 13: illegal multibyte sequence
```
![image](https://user-images.githubusercontent.com/33894721/62227860-418fa780-b3ef-11e9-9520-e8a208bc1c58.png)

download link:
https://e-hentai.org/g/901828/f58ef460a4/

無法異機還原，這個連結在其他電腦是可以下載的。但這個錯誤偶爾也會出現在下載其他連結的時候

最近因為E站要關了，所以十分緊急，懇請大神協助

**Comment by fffonion** [comment]
把rename_ori设成False，以及设置使用英文标题。

**Comment by neslxzhen** [comment]
你是指這樣嗎?還是我要去E網站的設定裡面改?
![image](https://user-images.githubusercontent.com/33894721/62277859-96780000-b479-11e9-88ae-32dae07d7b50.png)

**Comment by fffonion** [comment]
对的，可以这样试试

但是有些标题可能cp950还是解码不了，这个和#63类似是一个已知bug

**Comment by neslxzhen** [comment]
@fffonion 您好，十分感謝您撥冗回覆我。

不過同樣的連結還是會引發這個錯誤...

我正在嘗試編修，這看來是一個Bug，短期無解

**Comment by fffonion** [comment]
已push修复补丁，稍后上传exe

**Comment by fffonion** [comment]
可以到https://dl.yooooo.us/share/xeHentai/ 下载2.0.2.1测试版

**Comment by fffonion** [comment]
关闭不活动issue，如有问题请重新打开：）
