### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by Sylar846** [fffonion/xeHentai#66]
全部本子都无法下载，显示

ERROR - [23:23:45] 任务 #8087d161 发生错误: Traceback (most recent call last):
  File "xeHentai\core.py", line 203, in _do_task
  File "xeHentai\worker.py", line 136, in request
  File "xeHentai\filters.py", line 49, in flt_metadata
IndexError: list index out of range

**Comment by n40355** [comment]
應該說 裏站的本全都無法下載 不過裏站現在也不穩定 稍早還跳出憑證無效之類的
刪了"eh.log" "h.json" 重登後裏站網址還是無法下載，用表站網址只要活著的倒是沒問題

**Comment by fffonion** [comment]
我这好像没问题，感觉是因为刚搬家不太稳？

**Comment by n40355** [comment]
我這是只有
"下載穩定版->解壓->雙擊點我開始->登錄->輸入裏站地址->全部默認設置->錯誤Traceback" 
瀏覽器插件跟代理完全沒使用
還是現在亞洲IP有訪問限制或者帳號權限不足?
用表站功能就正常

**Comment by fffonion** [comment]
@n40355 浏览器能正常打开吗？如果可以的话，按照同样的代理设置配置下载器就可以啦

**Comment by n40355** [comment]
瀏覽器能正常打開 可是瀏覽器本來就沒用代理和其他插件阿

**Comment by wialny** [comment]
我这里也是遇到同样的情况
ERROR - [15:05:09] 任务 #4e1b607b 发生错误: Traceback (most recent call last):
  File "xeHentai\core.py", line 203, in _do_task
  File "xeHentai\worker.py", line 136, in request
  File "xeHentai\filters.py", line 49, in flt_metadata
IndexError: list index out of range
问题只出在exhentai, 同样的地址e-hentai就没问题
而且是更新24 May的2.0.2.0才出现的, 之前也是2.0.2.0就没问题, 但我直接覆盖了, 现在没有以前2.0.2.0了. 退回到2.0.1.9也可以正常下载

**Comment by n40355** [comment]
照樓上說的試了一下
2020不管是測試 穩定 還是一般版都是Traceback
2019一般版 測試版的確能正常下載裏站

**Comment by Aniark** [comment]
```
# also use proxy to download images
proxy_image = True
# only use proxy on images, not webpages
# if set to True, the value of proxy_image will be ignored
proxy_image_only = False

```
试试把proxy_image_only设置为False
我在这个设置下使用美国ss代理，可以下载

**Comment by Ending2015a** [comment]
改成 2.019 可以正常下載 :+1:

**Comment by neslxzhen** [comment]
改成 2.019 可以正常下載 👍

**Comment by Sylar846** [comment]
改回19可以了

**Comment by fffonion** [comment]
哦我忘记了自带的抗dns污染
https://github.com/fffonion/xeHentai/blob/dev/xeHentai/const.py#L55
这个ip要改成新的

**Comment by fffonion** [comment]
可以到https://dl.yooooo.us/share/xeHentai/下载2.0.2.1测试版

**Comment by fffonion** [comment]
关闭不活动issue，如有问题请重新打开：）

**Comment by JoshuaWuSama** [comment]
ERROR - [21:23:59] 任务 #84b24cd2 发生错误: Traceback (most recent call last):
  File "xeHentai\core.py", line 207, in _do_task
  File "xeHentai\worker.py", line 136, in request
  File "xeHentai\filters.py", line 49, in flt_metadata
IndexError: list index out of range

author你好，我这边又有这个问题了，一台电脑有一台电脑没有，我甚至无法定位错误原因，所有的版本都试过了都有这个问题，不确定为啥
