### ISSUE TITLE
rpc 任务添加似乎会触发 ban ip

### ISSUE THREAD

**Issue by telessa** [fffonion/xeHentai#69]
版本2.0.2.1
rpc添加任务超过连续添加两页以上 就很容易触发ban ip
选择下载原图 有捐金星 点数没有到达上限 
下载线程1 2 3 都是一样触发
下载线程5 似乎最容易直接被ban 与添加任务似乎没什么关系
表里站  用不用代理 都会触发
开启save tasks 后 如果添加两页以上 重启后似乎也容易触发

目前已连续触发累计 ban 3天处罚 刚解除

另使用代理 出现网络波动情况下
出现连续 以下提示 是修改超时等待时间 还是只能重开？
一天重开需要手动多次 颇为麻烦 
[Oct 15 18:21:15] 任务 #12938c23 开始
[Oct 15 18:21:15] 任务 #12938c23 发生错误: Traceback (most recent call last):
  File "xeHentai\core.py", line 203, in _do_task
  File "xeHentai\worker.py", line 92, in request
  File "xeHentai\proxy.py", line 38, in proxied_request
PoolException: try to use proxy but no proxies avaliable

[Oct 15 18:21:19] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:21:24] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:21:29] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:21:34] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:21:39] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:21:44] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:21:49] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:21:54] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:21:59] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:22:04] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:22:09] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:22:14] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:22:20] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:22:25] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:22:30] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:22:35] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:22:40] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:22:45] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:22:50] 绅士 2R/0Z, 队列 0R/0D
[Oct 15 18:22:50] 任务 #517360a4 卡住了, 可能是脚本有bug, 或者网络连接太慢了

不用代理 则是
Exception in thread monitorc19de541:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "xeHentai\worker.py", line 367, in run
  File "xeHentai\task.py", line 335, in rename_fname
  File "re.py", line 155, in sub
TypeError: expected string or buffer

**Comment by dennySORA** [comment]
這段時間我這邊也發生了這問題。
不知為什麼。

**Comment by fffonion** [comment]
被ban ip和使用rpc没有联系，只和一定时间内打开网页（扫描线程）的数量有关系。
可以考虑添加多个代理，这样ban了可以自动换
