### ISSUE TITLE
exhentai無法下載 但e-hentai可以

### ISSUE THREAD

**Issue by adern9** [fffonion/xeHentai#73]
有搭配xehentai Helper v0.16使用

下載 https://exhentai.org/g/1487328/845de49e52/ 的情形
![image](https://user-images.githubusercontent.com/7557690/69904169-7bdd7580-13de-11ea-9991-a08d9702feab.png)

下載 https://e-hentai.org/g/1487328/845de49e52/ 的情形
![image](https://user-images.githubusercontent.com/7557690/69904197-dd9ddf80-13de-11ea-8552-76be4472798e.png)

我記得上次使用是幾個月前，並沒出現這個問題。請問我應該怎麼做呢？

#ConnectTimeoutError
#HTTPSConnectionPool
#timeout
#AttributeError

**Comment by fffonion** [comment]
exhentai搬家了，请使用2.021版 （https://dl.yooooo.us/share/xeHentai/）

**Comment by fffonion** [comment]
如有问题请重新打开issue ：)
