### ISSUE TITLE
配額問題

### ISSUE THREAD

**Issue by qq123450000** [fffonion/xeHentai#80]
我的配額上限是10000
但是下載超過5000以後會報錯
可以怎麼解決??

**Comment by fffonion** [comment]
程序内有登陆帐号吗？

**Comment by qq123450000** [comment]
有

**Comment by fffonion** [comment]
可能是缺了perks的cookie，试一下通过用户脚本(https://github.com/fffonion/xeHentaiHelper.user.js) 添加一个任务同步一下cookie？

**Comment by qq123450000** [comment]
請問 點擊 "导出选中项到xeHentai"
會有甚麼回應嗎
我點了以後沒回應

**Comment by fffonion** [comment]
程序需要启动RPC模式，可以参考这个教程 https://dl.yooooo.us/share/xeHentai/xeHentai-2.0%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.mp4

**Comment by qq123450000** [comment]
可以了,謝謝!
