### ISSUE TITLE
黄字错误发生

### ISSUE THREAD

**Issue by skbamboo** [fffonion/xeHentai#83]
WARN - [09:20:58] 绅士-main GET https://exhentai.org/g/771315/8b3abd3fc1/: SOCKSHTTPSConnectionPool(host='exhentai.org', port=443): Max retries exceeded with url: /g/771315/8b3abd3fc1/ (Caused by ReadTimeoutError("SOCKSHTTPSConnectionPool(host='exhentai.org', port=443): Read timed out. (read timeout=20)",))
是什么状况，麻烦跟进下
![QQ截图20201128092042](https://user-images.githubusercontent.com/13145493/100490961-00caae80-315b-11eb-8902-3467e64ab898.png)

**Comment by fffonion** [comment]
看起来像是代理的问题，可以尝试换一个代理
