### ISSUE TITLE
里站进不去了

### ISSUE THREAD

**Issue by fat-john** [fffonion/xeHentai#84]
现在是白屏。看cookies，里面的ig的值是mestery。
请问现在还有熊猫书签之类的工具吗？或者目前有没有什么能用的cookies或者h.josn文件可以分享一下吗？

**Comment by fffonion** [comment]
清一下cookie重新登陆吧，比如chrome可以用这个插件 https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en
