### ISSUE TITLE
failed to download with SSL error message

### ISSUE THREAD

**Issue by d8888** [fffonion/xeHentai#86]
WARN - [13:15:48] 紳士-main GET https://e-hentai.org/g/xxxxxxx/xxxxxxxxxx/: HTTPSConnectionPool(host='104.20.27.25', port=443): Max retries exceeded with url:
/g/1635595/13cc13d2e0/ (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))
WARN - [13:15:49] 紳士-main GET https://e-hentai.org/g/xxxxxxx/xxxxxxxxxx/: HTTPSConnectionPool(host='104.20.26.25', port=443): Max retries exceeded with url:
/g/1635595/13cc13d2e0/ (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),)

**Comment by fffonion** [comment]
已修复，请使用程序自带的更新功能更新：）
