### ISSUE TITLE
你好，我是刚接触kong的小白大学生。

### ISSUE THREAD

**Issue by lizitao-sys** [fffonion/xeHentai#87]
我再使用kong-grpcgateway的插件时发现了一些问题，希望能请教一下你！如果方便能留下个联系方式吗？非常感谢，抱歉以这种方式联系你。

**Comment by lizitao-sys** [comment]
邮箱也可以！谢谢

**Comment by fffonion** [comment]
你好，可以 fffonion@gmail.com

**Comment by lizitao-sys** [comment]
你好！非常感谢你的回复！我在使用kong的grpc-gateway插件时，发现两个问题。第一个是查询参数的问题，如果查询参数是通过传统方式 ？name=1&amp;name=2，kong解析url时会将这些也当成方法的一部分传给grpc。第二个问题是返回的http code一直是200，不会跟随grpc-status设置的变化，例如我在grpc返回的是BadRequest，http code应该是400才对。我在issue上看到你已经修复这两个问题并且merge到master上了。如果可以的话，我想知道这两个问题是不是已经解决了，并且什么时候可以发一个release版本，然后我在使用kong的时候能使用到你已经更新好的grpc-gateway版本。如果需要一段时间才能更新，那我应该怎么样才能测试你到你现在最新的master版本呢？需要怎么才能更换新的版本插件进行测试？因为目前我是需要对api-gateway进行选型预研，所以想测试一下这方面的功能




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fffonion/xeHentai"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月9日(星期三) 下午4:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fffonion/xeHentai] 你好，我是刚接触kong的小白大学生。 (#87)





 
Closed #87.
