### ISSUE TITLE
似乎出了点问题

### ISSUE THREAD

**Issue by dffxd-suntra** [fffonion/xeHentai#91]
![image](https://user-images.githubusercontent.com/47025714/160243222-8ef3a6c7-8572-4839-932c-709395d5ef13.png)

没有连接上,我的win可以用,linux就不行了,py2和py3都试过

**Comment by BILLfreevpn** [comment]
any bodys?有人吗?

**Comment by fffonion** [comment]
网络问题，搞个代理试试

**Comment by dffxd-suntra** [comment]
就是香港的独立ip啊
