### ISSUE TITLE
希望能跳过下载卡住的任务

### ISSUE THREAD

**Issue by telessa** [fffonion/xeHentai#92]
版本  xeHentai 2.023-cab811e(2.023)
失败: 1013 
INFO - [20:57:38] 绅士 6R/0Z, 队列 0R/244D, 79.58 KB/s
DEBG - [20:57:41] 绅士-down-5 已下载图片 #186 Vampire_Master_1_189.jpg
INFO - [20:57:43] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:57:48] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:57:53] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:57:58] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:58:03] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:58:08] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:58:13] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:58:18] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:58:23] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:58:28] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:58:33] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:58:38] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:58:43] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:58:48] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:58:53] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:58:58] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:59:04] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:59:09] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:59:14] 绅士 6R/0Z, 队列 0R/245D, 0 B/s
INFO - [20:59:14] 任务 #79d81f9f 剩余以下图片未下载: [230]
WARN - [20:59:14] 任务 #79d81f9f 卡住了, 可能是脚本有bug, 或者网络连接太慢了

或者 

VERB - [00:45:40] t-scan-1 start
VERB - [00:45:40] wait 5 threads in state 10
WARN - [00:45:40] 绅士-scan-1 try to use proxy but no proxies avaliable
VERB - [00:45:40] t-scan-1 exit
INFO - [00:45:45] 绅士 5R/0Z, 队列 0R/0D, 0 B/s
INFO - [00:45:50] 绅士 5R/0Z, 队列 0R/0D, 0 B/s
INFO - [00:45:55] 绅士 5R/0Z, 队列 0R/0D, 0 B/s
INFO - [00:46:00] 绅士 5R/0Z, 队列 0R/0D, 0 B/s
INFO - [00:46:05] 绅士 5R/0Z, 队列 0R/0D, 0 B/s
INFO - [00:46:10] 绅士 5R/0Z, 队列 0R/0D, 0 B/s
Exception in thread monitor61a30499:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "xeHentai\worker.py", line 394, in run
KeyError: 'down-5'
执行不了几分钟 就会有这样的提示 然后只能手动重启 网页都是能顺畅打开的 
希望能跳过卡住任务 继续执行 
在开了完成任务压缩的选项后 剩下的自然就是未完成的任务文件夹 也好手动处理

**Comment by wialny** [comment]
这个问题还会影响到重命名. 只要有一个图片下载卡住, 那么就无法完成重命名. 关了重来只会下载之前没下载的图片并重命名, 之前已经下载的并不会被重命名, 只能删掉全部重下

**Comment by yumo137** [comment]
附议，只能在卡住了后手动暂停换下一个任务，下载的时候只能不断检查有没有卡住，有时候忘了看就一直卡在那边

**Comment by dffxd-suntra** [comment]
我试试自己做一个

**Comment by fffonion** [comment]
如有问题请重新打开issue：）
