### ISSUE TITLE
下载出错并疯狂吞掉配额

### ISSUE THREAD

**Issue by LoLumine** [fffonion/xeHentai#93]
请教一个问题。
在下载数量超过400张的图集时，经常会出现下面这种情况，一旦出现这个，下载配额会被疯狂吞掉。好像是一条提示要吞掉10点的下载配额。而且它会一直重复这个错误，直到所有的配额全部消耗完为止。
请问有任何办法避免这个吗？或者是在出现这种情况后能让下载自动停止下来吗？以避免吞掉所有的配额。

DEBG - [00:18:43] 绅士-down-1 下载图片 #574 时出错: 连接有问题？, 将在稍后重试
DEBG - [00:18:44] 绅士-down-1 下载图片 #575 时出错: 下载链接不太正常, 将在稍后重试
DEBG - [00:18:44] 绅士-down-1 下载图片 #576 时出错: 下载链接不太正常, 将在稍后重试
DEBG - [00:18:45] 绅士-down-1 下载图片 #577 时出错: 下载链接不太正常, 将在稍后重试

**Comment by fffonion** [comment]
建议更换代理，可能是代理的稳定性问题
