### ISSUE TITLE
”换源重新下载“功能似乎没有生效

### ISSUE THREAD

**Issue by Aniark** [fffonion/xeHentai#94]
使用的客户端版本：
> 从官网 https://dl.yooooo.us/share/xeHentai/ 下载的 xeHentai-2.0.2.3-稳定版.exe.zip，已配置更新到测试分支

发现问题的过程：
> 同时使用代理来下载图片和扫描网页，代理在下载到某张图片时会卡住不动

解决问题的临时方法：

> 切换另一个代理下载，或者手动到下载失败的图片页面下方点击 `Click here if the image fails loading` ，再手动保存到本地

初步推测问题产生的原因：

> 从切换代理后能正常访问来看（日志显示访问的是同一图片链接），可能是某些 H@H 客户端的主人配置防火墙屏蔽了代理的 IP

config.py 里有这么一行设置，预期应当会重新换源下载
```
# 设置最低下载速度，低于此值将换源重新下载
low_speed_threshold = 10
```

但检查日志后发现 xeHentai 每次都会从无法访问的链接下载，并没有换源重新下载

**Comment by fffonion** [comment]
可以同时在配置中添加多个代理，如果判断是代理的问题，并且代理池中没有代理，是不会触发换源下载的
