### ISSUE TITLE
從10/25開始就不行使用了

### ISSUE THREAD

**Issue by Arbiter2012** [fffonion/xeHentai#99]
**這是里站**
![ScreenShot_20241026190500](https://github.com/user-attachments/assets/10ae2264-8062-4894-bedf-5972cf5f2013)

**這是表站**
![ScreenShot_20241026191009](https://github.com/user-attachments/assets/87941d3d-8c8e-44f5-af55-d9e9a4b8ee6f)

**用網頁使用沒問題
就是從昨日下午開始不能下載**
**謝謝大大解答**

**Comment by fffonion** [comment]
我知道了，multi page viewer的判断坏了，现在修好了。用自动更新就可以获取修复了：）

**Comment by Kin-Chi** [comment]
![2024-10-27 020323](https://github.com/user-attachments/assets/784a66ba-72b3-4696-9214-187606bad3c5)
似乎还是不行，请问客户端这里还需要做什么尝试吗？

**Comment by Arbiter2012** [comment]
**重新下載[xeHentai-2.0.2.3.exe.zip]覆蓋原本的之後
就變成如下情況**

![ScreenShot_20241027023807](https://github.com/user-attachments/assets/c79d5ba7-280a-4e84-b89b-b5474e29a9dc)

系統使用的是win7

**Comment by Arbiter2012** [comment]
> 我知道了，multi page viewer的判断坏了，现在修好了。用自动更新就可以获取修复了：）

**重新下載[xeHentai-2.0.2.3.exe.zip]覆蓋原本的之後
就變成如下情況**

![ScreenShot_20241027023807](https://github.com/user-attachments/assets/c79d5ba7-280a-4e84-b89b-b5474e29a9dc)

系統使用的是win7

**Comment by ZhuolunZhong** [comment]
把设置里的Gallery Page Thumbnail Labeling改为NONE，我本来也出了这个问题，在https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1480这边看到了可能相关的讨论，改了设置，就没问题了

**Comment by Arbiter2012** [comment]
> 把设置里的Gallery Page Thumbnail Labeling改为NONE，我本来也出了这个问题，在[xiaojieonly/Ehviewer_CN_SXJ#1480](https://github.com/xiaojieonly/Ehviewer_CN_SXJ/issues/1480) 这边看到了可能相关的讨论，改了设置，就没问题了

設置原本就是
![ScreenShot_20241027163247](https://github.com/user-attachments/assets/04200528-2201-4c69-8b73-da6e5ba23ba4)

**Comment by Arbiter2012** [comment]
**10/27
現在安裝了Python 3.11.4後
也把資料夾_internal放在同目錄下
16:35更新
16:42可以正常使用了**
![ScreenShot_20241027164205](https://github.com/user-attachments/assets/ca67d292-3255-457b-b1da-ba5ecb98cb50)

**Comment by Arbiter2012** [comment]
> 我知道了，multi page viewer的判断坏了，现在修好了。用自动更新就可以获取修复了：）

**10/27
現在安裝了Python 3.11.4後
也把資料夾_internal放在同目錄下**
![ScreenShot_20241027164327](https://github.com/user-attachments/assets/7fec6c3e-ae86-4011-b244-1b70b65f5418)

**16:35自動更新
16:42可以正常使用了****
![ScreenShot_20241027164205](https://github.com/user-attachments/assets/ca67d292-3255-457b-b1da-ba5ecb98cb50)
